// Mock data for Automation & Security module

// Roles & Permissions Data
export const rolesData = [
  {
    id: 'role-admin',
    name: 'Admin',
    description: 'Full system access with all permissions',
    permissions: {
      orders: { read: true, write: true, approve: true },
      sellers: { read: true, write: true, approve: true },
      customers: { read: true, write: true, approve: true },
      products: { read: true, write: true, approve: true },
      settings: { read: true, write: true, approve: true },
      analytics: { read: true, write: true, approve: true },
      marketing: { read: true, write: true, approve: true },
      security: { read: true, write: true, approve: true },
    },
    userCount: 3,
  },
  {
    id: 'role-manager',
    name: 'Manager / Staff',
    description: 'Management access with limited approval rights',
    permissions: {
      orders: { read: true, write: true, approve: false },
      sellers: { read: true, write: true, approve: false },
      customers: { read: true, write: true, approve: false },
      products: { read: true, write: true, approve: false },
      settings: { read: true, write: false, approve: false },
      analytics: { read: true, write: false, approve: false },
      marketing: { read: true, write: true, approve: false },
      security: { read: true, write: false, approve: false },
    },
    userCount: 8,
  },
  {
    id: 'role-support',
    name: 'Support',
    description: 'Customer support with read-only access to most areas',
    permissions: {
      orders: { read: true, write: false, approve: false },
      sellers: { read: true, write: false, approve: false },
      customers: { read: true, write: true, approve: false },
      products: { read: true, write: false, approve: false },
      settings: { read: false, write: false, approve: false },
      analytics: { read: false, write: false, approve: false },
      marketing: { read: false, write: false, approve: false },
      security: { read: false, write: false, approve: false },
    },
    userCount: 12,
  },
]

// Users with Role Assignments
export const usersWithRoles = [
  {
    id: 'user-001',
    name: 'Admin User',
    email: 'admin@example.com',
    roleId: 'role-admin',
    roleName: 'Admin',
    status: 'active',
    lastLogin: '2024-01-17T14:30:00Z',
  },
  {
    id: 'user-002',
    name: 'Manager One',
    email: 'manager1@example.com',
    roleId: 'role-manager',
    roleName: 'Manager / Staff',
    status: 'active',
    lastLogin: '2024-01-17T10:15:00Z',
  },
  {
    id: 'user-003',
    name: 'Support Agent',
    email: 'support1@example.com',
    roleId: 'role-support',
    roleName: 'Support',
    status: 'active',
    lastLogin: '2024-01-17T09:00:00Z',
  },
  {
    id: 'user-004',
    name: 'Manager Two',
    email: 'manager2@example.com',
    roleId: 'role-manager',
    roleName: 'Manager / Staff',
    status: 'active',
    lastLogin: '2024-01-16T16:45:00Z',
  },
  {
    id: 'user-005',
    name: 'Support Agent Two',
    email: 'support2@example.com',
    roleId: 'role-support',
    roleName: 'Support',
    status: 'active',
    lastLogin: '2024-01-17T08:30:00Z',
  },
]

// Audit Logs Data
export const auditLogsData = [
  {
    id: 'audit-001',
    userId: 'user-001',
    userName: 'Admin User',
    userEmail: 'admin@example.com',
    action: 'Order Status Updated',
    actionType: 'order_update',
    entityType: 'order',
    entityId: 'ORD-2024-001',
    changes: {
      field: 'status',
      oldValue: 'PENDING',
      newValue: 'SHIPPED',
    },
    timestamp: '2024-01-17T14:25:00Z',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
  },
  {
    id: 'audit-002',
    userId: 'user-001',
    userName: 'Admin User',
    userEmail: 'admin@example.com',
    action: 'Seller Verified',
    actionType: 'seller_verification',
    entityType: 'seller',
    entityId: 'seller-003',
    changes: {
      field: 'verificationStatus',
      oldValue: 'pending',
      newValue: 'approved',
    },
    timestamp: '2024-01-17T13:45:00Z',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
  },
  {
    id: 'audit-003',
    userId: 'user-002',
    userName: 'Manager One',
    userEmail: 'manager1@example.com',
    action: 'Refund Approved',
    actionType: 'refund_approval',
    entityType: 'order',
    entityId: 'ORD-2024-002',
    changes: {
      field: 'refundStatus',
      oldValue: 'pending',
      newValue: 'approved',
      amount: 150.00,
    },
    timestamp: '2024-01-17T12:30:00Z',
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
  },
  {
    id: 'audit-004',
    userId: 'user-001',
    userName: 'Admin User',
    userEmail: 'admin@example.com',
    action: 'Settings Changed',
    actionType: 'settings_change',
    entityType: 'settings',
    entityId: 'platform-settings',
    changes: {
      field: 'platformName',
      oldValue: 'E-Commerce Platform',
      newValue: 'Zizla Marketplace',
    },
    timestamp: '2024-01-17T11:15:00Z',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
  },
  {
    id: 'audit-005',
    userId: 'user-003',
    userName: 'Support Agent',
    userEmail: 'support1@example.com',
    action: 'Customer Support Ticket Updated',
    actionType: 'support_update',
    entityType: 'ticket',
    entityId: 'ticket-001',
    changes: {
      field: 'status',
      oldValue: 'open',
      newValue: 'in-progress',
    },
    timestamp: '2024-01-17T10:00:00Z',
    ipAddress: '192.168.1.102',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
  },
  {
    id: 'audit-006',
    userId: 'user-001',
    userName: 'Admin User',
    userEmail: 'admin@example.com',
    action: 'Coupon Created',
    actionType: 'coupon_create',
    entityType: 'coupon',
    entityId: 'coupon-007',
    changes: {
      field: 'new',
      oldValue: null,
      newValue: 'WELCOME25',
    },
    timestamp: '2024-01-16T16:20:00Z',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
  },
  {
    id: 'audit-007',
    userId: 'user-002',
    userName: 'Manager One',
    userEmail: 'manager1@example.com',
    action: 'Order Cancelled',
    actionType: 'order_cancel',
    entityType: 'order',
    entityId: 'ORD-2024-005',
    changes: {
      field: 'status',
      oldValue: 'PENDING',
      newValue: 'CANCELLED',
      reason: 'Customer request',
    },
    timestamp: '2024-01-16T15:10:00Z',
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
  },
  {
    id: 'audit-008',
    userId: 'user-001',
    userName: 'Admin User',
    userEmail: 'admin@example.com',
    action: 'User Role Changed',
    actionType: 'role_change',
    entityType: 'user',
    entityId: 'user-004',
    changes: {
      field: 'role',
      oldValue: 'Support',
      newValue: 'Manager / Staff',
    },
    timestamp: '2024-01-16T14:00:00Z',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
  },
]

// Invoice Settings Data
export const invoiceSettingsData = {
  autoGenerate: true,
  invoicePrefix: 'INV',
  invoiceNumberFormat: '',
  nextInvoiceNumber: 1245,
  template: 'default',
  includeTax: true,
  includeShipping: true,
  companyInfo: {
    name: 'Zizla Marketplace',
    address: '123 Business Street, City, Country',
    taxId: 'TAX-123456789',
    email: 'invoices@zizla.com',
    phone: '+1234567890',
  },
}

// Invoice Status per Order
export const invoiceStatusData = [
  {
    orderId: 'ORD-2024-001',
    invoiceNumber: 'INV-2024-01-1240',
    status: 'generated',
    generatedAt: '2024-01-15T10:30:00Z',
    downloadUrl: '#',
  },
  {
    orderId: 'ORD-2024-002',
    invoiceNumber: 'INV-2024-01-1241',
    status: 'generated',
    generatedAt: '2024-01-15T11:15:00Z',
    downloadUrl: '#',
  },
  {
    orderId: 'ORD-2024-003',
    invoiceNumber: null,
    status: 'pending',
    generatedAt: null,
    downloadUrl: null,
  },
  {
    orderId: 'ORD-2024-004',
    invoiceNumber: null,
    status: 'failed',
    generatedAt: null,
    downloadUrl: null,
    error: 'Template generation failed',
  },
  {
    orderId: 'ORD-2024-005',
    invoiceNumber: 'INV-2024-01-1242',
    status: 'generated',
    generatedAt: '2024-01-16T09:20:00Z',
    downloadUrl: '#',
  },
]

// System Alerts Data
export const systemAlertsData = [
  {
    id: 'alert-001',
    type: 'critical',
    title: 'Multiple Failed Login Attempts',
    message: '5 failed login attempts detected from IP 192.168.1.200',
    timestamp: '2024-01-17T14:45:00Z',
    read: false,
    action: 'security',
  },
  {
    id: 'alert-002',
    type: 'warning',
    title: 'High Order Volume',
    message: 'Order volume increased by 150% in the last hour',
    timestamp: '2024-01-17T14:30:00Z',
    read: false,
    action: 'orders',
  },
  {
    id: 'alert-003',
    type: 'info',
    title: 'New Seller Registration',
    message: 'A new seller has completed registration and is pending verification',
    timestamp: '2024-01-17T14:15:00Z',
    read: true,
    action: 'sellers',
  },
  {
    id: 'alert-004',
    type: 'critical',
    title: 'Payment Gateway Error',
    message: 'Payment gateway API returned error code 500',
    timestamp: '2024-01-17T13:00:00Z',
    read: false,
    action: 'payments',
  },
  {
    id: 'alert-005',
    title: 'System Backup Completed',
    message: 'Daily system backup completed successfully',
    timestamp: '2024-01-17T02:00:00Z',
    read: true,
    action: 'system',
  },
]

