'use client'
import { createContext, useContext, useState, useEffect } from 'react'

const LanguageCurrencyContext = createContext()

export const useLanguageCurrency = () => {
  const context = useContext(LanguageCurrencyContext)
  if (!context) {
    throw new Error('useLanguageCurrency must be used within LanguageCurrencyProvider')
  }
  return context
}

// Translation files
const translations = {
  English: {
    shop: 'Shop',
    cart: 'Cart',
    wishlist: 'Wishlist',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    profile: 'My Profile',
    orders: 'My Orders',
    search: 'Search...',
    all: 'All',
    home: 'Home',
    privacyPolicy: 'Privacy Policy',
    getSupport: 'Get Support',
    submit: 'Submit',
    tellYourQuery: 'Tell your query',
    describeIssue: 'Describe your issue or question here...',
    submitQuery: 'Submit your query or contact us directly on WhatsApp',
    contactOnWhatsApp: 'Contact on WhatsApp',
    welcome: 'Welcome to Zizla',
    description: 'your ultimate destination for the latest and smartest gadgets. From smartphones and smartwatches to essential accessories, we bring you the best in innovation — all in one place.',
    copyright: 'Copyright 2025 © Zizla All Right Reserved.',
    featuredProducts: 'FEATURED PRODUCTS',
    viewAllProducts: 'View All Products',
    website: 'WEBSITE?',
    contact: 'CONTACT',
    news: 'NEWS',
    freeShipping: 'Free Shipping Above $150!',
    startsFrom: 'Starts from',
    learnMore: 'LEARN MORE',
    zizlaYoullLove: 'Zizla you\'ll love. Prices you\'ll trust.',
    setLanguageCurrency: 'Set language and currency',
    setLanguage: 'Set language',
    selectPreferred: 'Select your preferred language and currency. You can update the settings at any time.',
    selectLanguagePreferred: 'Select your preferred language. You can update the settings at any time.',
    language: 'Language',
    currency: 'Currency',
    save: 'Save',
    loginRegister: 'Login / Register',
    becomeSeller: 'Become a Seller',
    loginAsSeller: 'Login as a seller',
    areYouSeller: 'Are you a seller?',
    dontHaveAccount: 'Don\'t have an account?',
    signUp: 'Sign up',
    continueWith: 'Or continue with',
    continueWithGoogle: 'Continue with Google',
    continueWithFacebook: 'Continue with Facebook',
    continueWithEmail: 'Continue with Email',
    welcomeBack: 'Welcome Back',
    signInToAccount: 'Sign in to your Zizla account',
    backToHome: 'Back to Home',
    demoCredentials: 'Demo Credentials',
    useTheseCredentials: 'Use these credentials to login:',
    fillDemoCredentials: 'Fill Demo Credentials',
    emailAddress: 'Email Address',
    enterYourEmail: 'Enter your email',
    enterYourPassword: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signingIn: 'Signing in...',
    signIn: 'Sign In',
    alreadyHaveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    joinZizla: 'Join Zizla and start shopping',
    fullName: 'Full Name',
    enterYourFullName: 'Enter your full name',
    createAPassword: 'Create a password',
    confirmPassword: 'Confirm Password',
    confirmYourPassword: 'Confirm your password',
    iAgreeTo: 'I agree to the',
    termsOfService: 'Terms of Service',
    creatingAccount: 'Creating Account...',
    createAccountButton: 'Create Account',
    becomeASeller: 'Become a Seller',
    joinZizlaAndStartSelling: 'Join Zizla and start selling your products to thousands of customers',
    signInToExistingSeller: 'Sign in to your existing seller account and access your dashboard',
    newToSelling: 'New to selling?',
    createSellerAccount: 'Create your seller account in just 5 simple steps and start selling today',
    getStarted: 'Get Started',
    whyChooseZizla: 'Why choose Zizla for selling?',
    quickSetup: 'Quick Setup',
    getStartedInMinutes: 'Get started in minutes with our simple registration process',
    lowFees: 'Low Fees',
    competitiveCommissionRates: 'Competitive commission rates to maximize your profits',
    support247: '24/7 Support',
    roundTheClockAssistance: 'Round-the-clock assistance for all your selling needs',
    analytics: 'Analytics',
    detailedInsights: 'Detailed insights to grow your business',
    sellerDashboard: 'Seller Dashboard',
    welcomeBack: 'Welcome back',
    addProduct: 'Add Product',
    viewStore: 'View Store',
    salesDashboard: 'Sales Dashboard',
    logout: 'Logout',
    loadingDashboard: 'Loading dashboard...',
    welcomeToSellerCenter: 'Welcome to Zizla Seller Center!',
    accountCreatedSuccessfully: 'Your seller account has been created successfully. You can now start adding products and managing your store.',
    totalProducts: 'Total Products',
    totalOrders: 'Total Orders',
    totalRevenue: 'Total Revenue',
    netProfit: 'Net Profit',
    recentActivity: 'Recent Activity',
    accountCreated: 'Account Created',
    accountCreatedDesc: 'Your seller account has been successfully created',
    profileCompleted: 'Profile Completed',
    profileCompletedDesc: 'All registration steps have been completed',
    quickActions: 'Quick Actions',
    addNewProduct: 'Add New Product',
    manageProducts: 'Manage Products',
    viewOrders: 'View Orders',
    deliveryManagement: 'Delivery Management',
    yourBusinessInformation: 'Your Business Information',
    businessDetails: 'Business Details',
    name: 'Name',
    type: 'Type',
    email: 'Email',
    phone: 'Phone',
    categories: 'Categories',
    notProvided: 'Not provided',
    myProducts: 'My Products',
    manageYourProductInventory: 'Manage your product inventory',
    back: 'Back',
    loadingProducts: 'Loading products...',
    searchProducts: 'Search products...',
    filterByStatus: 'Filter by status',
    all: 'All',
    published: 'Published',
    draft: 'Draft',
    pending: 'Pending',
    noProductsFound: 'No products found',
    addYourFirstProduct: 'Add your first product to get started',
    productName: 'Product Name',
    price: 'Price',
    stock: 'Stock',
    status: 'Status',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    areYouSureDelete: 'Are you sure you want to delete this product?',
    addNewProductTitle: 'Add New Product',
    backToDashboard: 'Back to Dashboard',
    basicDetails: 'Basic Details',
    productTitle: 'Product Title',
    sku: 'SKU',
    category: 'Category',
    brand: 'Brand',
    pricingInventory: 'Pricing & Inventory',
    salePrice: 'Sale Price',
    stockQuantity: 'Stock Quantity',
    skuBarcode: 'SKU/Barcode',
    shippingDetails: 'Shipping Details',
    weight: 'Weight',
    dimensions: 'Dimensions',
    length: 'Length',
    width: 'Width',
    height: 'Height',
    media: 'Media',
    productImages: 'Product Images',
    uploadImages: 'Upload Images',
    videoUrl: 'Video URL (optional)',
    description: 'Description',
    shortDescription: 'Short Description',
    metaSeo: 'Meta/SEO',
    metaTitle: 'Meta Title',
    metaDescription: 'Meta Description',
    keywords: 'Keywords',
    saveAsDraft: 'Save as Draft',
    publishProduct: 'Publish Product',
    productSaved: 'Product saved successfully!',
    productPublished: 'Product published successfully!',
    pleaseFillRequired: 'Please fill in all required fields',
    sellerDeliveryOption: 'Seller Delivery Option',
    selfDelivery: 'Self Delivery',
    platformDelivery: 'Platform Delivery',
    selectCategory: 'Select Category',
    enterProductTitle: 'Enter product title',
    enterSku: 'Enter SKU',
    enterBrand: 'Enter brand name',
    enterPrice: 'Enter price',
    enterSalePrice: 'Enter sale price (optional)',
    enterStockQuantity: 'Enter stock quantity',
    enterSkuBarcode: 'Enter SKU/Barcode',
    enterWeight: 'Enter weight (kg)',
    enterLength: 'Enter length (cm)',
    enterWidth: 'Enter width (cm)',
    enterHeight: 'Enter height (cm)',
    enterVideoUrl: 'Enter video URL',
    enterDescription: 'Enter product description',
    enterShortDescription: 'Enter short description',
    enterMetaTitle: 'Enter meta title',
    enterMetaDescription: 'Enter meta description',
    enterKeywords: 'Enter keywords (comma separated)',
    dragToReorder: 'Drag to reorder images',
    removeImage: 'Remove image',
    editProduct: 'Edit Product',
    updateProduct: 'Update Product',
    productUpdated: 'Product updated successfully!',
    viewProduct: 'View Product',
    productDetails: 'Product Details',
    orders: 'Orders',
    delivery: 'Delivery',
    schedule: 'Schedule',
    continue: 'Continue',
    noProductsFound: 'No products found',
    noProductsYet: 'No products yet',
    tryAdjustingSearch: 'Try adjusting your search or filter criteria',
    getStartedByAdding: 'Get started by adding your first product',
    addYourFirstProduct: 'Add Your First Product',
    totalStock: 'Total Stock',
    stock: 'Stock',
    createNewProductForStore: 'Create a new product for your store',
    productTitleRequired: 'Product Title *',
    skuRequired: 'SKU *',
    categoryRequired: 'Category *',
    brandRequired: 'Brand *',
    priceRequired: 'Price *',
    salePriceOptional: 'Sale Price (optional)',
    stockQuantityRequired: 'Stock Quantity *',
    skuBarcodeOptional: 'SKU/Barcode (optional)',
    weightRequired: 'Weight (kg) *',
    lengthRequired: 'Length (cm) *',
    widthRequired: 'Width (cm) *',
    heightRequired: 'Height (cm) *',
    videoUrlOptional: 'Video URL (optional)',
    descriptionRequired: 'Description *',
    shortDescriptionOptional: 'Short Description (optional)',
    metaTitleOptional: 'Meta Title (optional)',
    metaDescriptionOptional: 'Meta Description (optional)',
    keywordsOptional: 'Keywords (optional)',
    categoryIsRequired: 'Category is required',
    weightIsRequired: 'Weight is required',
    productSavedSuccessfully: 'Product saved successfully!',
    productPublishedSuccessfully: 'Product published successfully!',
    failedToPublishProduct: 'Failed to publish product. Please try again.',
    pleaseFillInAllRequired: 'Please fill in all required fields',
    dragToReorderImages: 'Drag to reorder images',
    removeImage: 'Remove image',
    optional: 'Optional',
    enterSku: 'Enter SKU manually (e.g., ABC-12345)',
    cancel: 'Cancel',
    publishing: 'Publishing...',
    pleaseFixErrorsBeforePublishing: 'Please fix the errors before publishing',
    languageUpdated: 'Language updated',
    // Sales Dashboard
    trackSalesPerformance: 'Track your sales performance and earnings',
    loadingSalesData: 'Loading sales data...',
    welcomeToSalesDashboard: 'Welcome to your Sales Dashboard!',
    onceYouStartReceivingOrders: 'Once you start receiving orders, you\'ll see your sales performance, revenue, and fee breakdown here.',
    totalRevenue: 'Total Revenue',
    totalOrders: 'Total Orders',
    productsSold: 'Products Sold',
    netProfit: 'Net Profit',
    noDataAvailable: 'No data available',
    feeBreakdown: 'Fee Breakdown',
    platformFees: 'Platform Fees',
    deliveryFees: 'Delivery Fees',
    totalFees: 'Total Fees',
    ofTotalSales: 'of total sales',
    ofTotalRevenue: 'of total revenue',
    perOrder: 'per order',
    selfDeliveryNoFees: 'Self-delivery (no fees)',
    topSellingProducts: 'Top Selling Products',
    recentOrders: 'Recent Orders',
    noSalesDataAvailable: 'No sales data available for this period',
    noOrdersFoundForPeriod: 'No orders found for this period',
    sold: 'sold',
    item: 'item',
    items: 'items',
    averageOrderValue: 'Average Order Value',
    last7Days: 'Last 7 days',
    last30Days: 'Last 30 days',
    last90Days: 'Last 90 days',
    allTime: 'All time',
    // Orders Page
    manageCustomerOrders: 'Manage your customer orders',
    loadingOrders: 'Loading orders...',
    searchOrders: 'Search orders...',
    allStatus: 'All Status',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    order: 'Order',
    customerName: 'Customer Name',
    deliveryAddress: 'Delivery Address',
    orderItems: 'Order Items',
    qty: 'Qty',
    paymentMethod: 'Payment Method',
    delivery: 'Delivery',
    couponUsed: 'Coupon Used',
    totalAmount: 'Total Amount',
    orderDelayed: 'Order Delayed',
    expected: 'Expected',
    chatWithBuyer: 'Chat with Buyer',
    reviewBuyer: 'Review Buyer',
    viewReview: 'View Review',
    viewDetails: 'View Details',
    noOrdersFound: 'No orders found',
    tryAdjustingSearchOrFilter: 'Try adjusting your search or filter criteria',
    youHaventReceivedAnyOrdersYet: 'You haven\'t received any orders yet',
    // Delivery Page
    manageDeliveriesAndTrackOrders: 'Manage deliveries and track orders',
    deliveryOrders: 'Delivery Orders',
    proofOfDelivery: 'Proof of Delivery',
    parcelScanner: 'Parcel Scanner',
    deliverySchedule: 'Delivery Schedule',
    orderId: 'Order ID',
    distance: 'Distance',
    actions: 'Actions',
    viewRoute: 'View Route',
    packed: 'Packed',
    shipped: 'Shipped',
    outForDelivery: 'Out for Delivery',
    uploadProofOfDelivery: 'Upload Proof of Delivery',
    uploaded: 'Uploaded',
    noProofUploaded: 'No proof uploaded',
    uploadPhoto: 'Upload Photo',
    deliveryStatus: 'Delivery Status',
    pending: 'Pending',
    scanParcel: 'Scan Parcel',
    cameraFrame: 'Camera Frame',
    positionBarcodeWithinFrame: 'Position barcode/QR code within frame',
    recentScans: 'Recent Scans',
    timestamp: 'Timestamp',
    noScansYet: 'No scans yet',
    routeTo: 'Route to',
    from: 'From',
    to: 'To',
    warehouse: 'Warehouse',
    proofOfDeliveryUploadedSuccessfully: 'Proof of delivery uploaded successfully',
    parcelScannedSuccessfully: 'Parcel scanned successfully',
    customer: 'Customer',
    ofTotalSales: 'of total sales',
    updateYourProductInformation: 'Update your product information',
    updating: 'Updating...',
    failedToUpdateProduct: 'Failed to update product. Please try again.',
  },
  Spanish: {
    shop: 'Tienda',
    cart: 'Carrito',
    wishlist: 'Lista de deseos',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    logout: 'Cerrar sesión',
    profile: 'Mi Perfil',
    orders: 'Mis Pedidos',
    search: 'Buscar...',
    all: 'Todos',
    home: 'Inicio',
    privacyPolicy: 'Política de Privacidad',
    getSupport: 'Obtener Soporte',
    submit: 'Enviar',
    tellYourQuery: 'Cuéntanos tu consulta',
    describeIssue: 'Describe tu problema o pregunta aquí...',
    submitQuery: 'Envía tu consulta o contáctanos directamente en WhatsApp',
    contactOnWhatsApp: 'Contactar en WhatsApp',
    welcome: 'Bienvenido a Zizla',
    description: 'tu destino definitivo para los últimos y más inteligentes gadgets. Desde smartphones y smartwatches hasta accesorios esenciales, te traemos lo mejor en innovación, todo en un solo lugar.',
    copyright: 'Copyright 2025 © Zizla Todos los derechos reservados.',
    featuredProducts: 'PRODUCTOS DESTACADOS',
    viewAllProducts: 'Ver Todos los Productos',
    website: 'SITIO WEB?',
    contact: 'CONTACTO',
    news: 'NOTICIAS',
    freeShipping: '¡Envío Gratis por Compras Superiores a $150!',
    startsFrom: 'Desde',
    learnMore: 'SABER MÁS',
    zizlaYoullLove: 'Zizla que te encantará. Precios en los que confiarás.',
    setLanguageCurrency: 'Establecer idioma y moneda',
    setLanguage: 'Establecer idioma',
    selectPreferred: 'Selecciona tu idioma y moneda preferidos. Puedes actualizar la configuración en cualquier momento.',
    selectLanguagePreferred: 'Selecciona tu idioma preferido. Puedes actualizar la configuración en cualquier momento.',
    language: 'Idioma',
    currency: 'Moneda',
    save: 'Guardar',
    loginRegister: 'Iniciar sesión / Registrarse',
    becomeSeller: 'Convertirse en Vendedor',
    loginAsSeller: 'Iniciar sesión como vendedor',
    areYouSeller: '¿Eres vendedor?',
    dontHaveAccount: '¿No tienes una cuenta?',
    signUp: 'Regístrate',
    continueWith: 'O continuar con',
    continueWithGoogle: 'Continuar con Google',
    continueWithFacebook: 'Continuar con Facebook',
    continueWithEmail: 'Continuar con Email',
    welcomeBack: 'Bienvenido de Nuevo',
    signInToAccount: 'Inicia sesión en tu cuenta de Zizla',
    backToHome: 'Volver al Inicio',
    demoCredentials: 'Credenciales de Demostración',
    useTheseCredentials: 'Usa estas credenciales para iniciar sesión:',
    fillDemoCredentials: 'Llenar Credenciales de Demostración',
    emailAddress: 'Dirección de Correo',
    enterYourEmail: 'Ingresa tu correo',
    enterYourPassword: 'Ingresa tu contraseña',
    rememberMe: 'Recordarme',
    forgotPassword: '¿Olvidaste tu contraseña?',
    signingIn: 'Iniciando sesión...',
    signIn: 'Iniciar Sesión',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    createAccount: 'Crear Cuenta',
    joinZizla: 'Únete a Zizla y comienza a comprar',
    fullName: 'Nombre Completo',
    enterYourFullName: 'Ingresa tu nombre completo',
    createAPassword: 'Crea una contraseña',
    confirmPassword: 'Confirmar Contraseña',
    confirmYourPassword: 'Confirma tu contraseña',
    iAgreeTo: 'Acepto los',
    termsOfService: 'Términos de Servicio',
    creatingAccount: 'Creando Cuenta...',
    createAccountButton: 'Crear Cuenta',
    becomeASeller: 'Convertirse en Vendedor',
    joinZizlaAndStartSelling: 'Únete a Zizla y comienza a vender tus productos a miles de clientes',
    signInToExistingSeller: 'Inicia sesión en tu cuenta de vendedor existente y accede a tu panel',
    newToSelling: '¿Nuevo en las ventas?',
    createSellerAccount: 'Crea tu cuenta de vendedor en solo 5 pasos simples y comienza a vender hoy',
    getStarted: 'Comenzar',
    whyChooseZizla: '¿Por qué elegir Zizla para vender?',
    quickSetup: 'Configuración Rápida',
    getStartedInMinutes: 'Comienza en minutos con nuestro proceso de registro simple',
    lowFees: 'Tarifas Bajas',
    competitiveCommissionRates: 'Tarifas de comisión competitivas para maximizar tus ganancias',
    support247: 'Soporte 24/7',
    roundTheClockAssistance: 'Asistencia las 24 horas para todas tus necesidades de venta',
    analytics: 'Analíticas',
    detailedInsights: 'Información detallada para hacer crecer tu negocio',
  },
  French: {
    shop: 'Boutique',
    cart: 'Panier',
    wishlist: 'Liste de souhaits',
    login: 'Connexion',
    register: 'S\'inscrire',
    logout: 'Déconnexion',
    profile: 'Mon Profil',
    orders: 'Mes Commandes',
    search: 'Rechercher...',
    all: 'Tous',
    home: 'Accueil',
    privacyPolicy: 'Politique de Confidentialité',
    getSupport: 'Obtenir de l\'Aide',
    submit: 'Soumettre',
    tellYourQuery: 'Dites-nous votre question',
    describeIssue: 'Décrivez votre problème ou question ici...',
    submitQuery: 'Soumettez votre question ou contactez-nous directement sur WhatsApp',
    contactOnWhatsApp: 'Contacter sur WhatsApp',
    welcome: 'Bienvenue chez Zizla',
    description: 'votre destination ultime pour les derniers gadgets les plus intelligents. Des smartphones et montres intelligentes aux accessoires essentiels, nous vous apportons le meilleur de l\'innovation, le tout en un seul endroit.',
    copyright: 'Copyright 2025 © Zizla Tous droits réservés.',
    featuredProducts: 'PRODUITS EN VEDETTE',
    viewAllProducts: 'Voir Tous les Produits',
    website: 'SITE WEB?',
    contact: 'CONTACT',
    news: 'ACTUALITÉS',
    freeShipping: 'Livraison Gratuite au-dessus de 150 $!',
    startsFrom: 'À partir de',
    learnMore: 'EN SAVOIR PLUS',
    zizlaYoullLove: 'Zizla que vous adorerez. Des prix auxquels vous ferez confiance.',
    setLanguageCurrency: 'Définir la langue et la devise',
    setLanguage: 'Définir la langue',
    selectPreferred: 'Sélectionnez votre langue et devise préférées. Vous pouvez mettre à jour les paramètres à tout moment.',
    selectLanguagePreferred: 'Sélectionnez votre langue préférée. Vous pouvez mettre à jour les paramètres à tout moment.',
    language: 'Langue',
    currency: 'Devise',
    save: 'Enregistrer',
    loginRegister: 'Connexion / Inscription',
    becomeSeller: 'Devenir Vendeur',
    loginAsSeller: 'Se connecter en tant que vendeur',
    areYouSeller: 'Êtes-vous vendeur?',
    dontHaveAccount: 'Vous n\'avez pas de compte?',
    signUp: 'S\'inscrire',
    continueWith: 'Ou continuer avec',
    continueWithGoogle: 'Continuer avec Google',
    continueWithFacebook: 'Continuer avec Facebook',
    continueWithEmail: 'Continuer avec Email',
    welcomeBack: 'Bon Retour',
    signInToAccount: 'Connectez-vous à votre compte Zizla',
    backToHome: 'Retour à l\'Accueil',
    demoCredentials: 'Identifiants de Démonstration',
    useTheseCredentials: 'Utilisez ces identifiants pour vous connecter:',
    fillDemoCredentials: 'Remplir les Identifiants de Démonstration',
    emailAddress: 'Adresse E-mail',
    enterYourEmail: 'Entrez votre e-mail',
    enterYourPassword: 'Entrez votre mot de passe',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié?',
    signingIn: 'Connexion en cours...',
    signIn: 'Se Connecter',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    createAccount: 'Créer un Compte',
    joinZizla: 'Rejoignez Zizla et commencez à magasiner',
    fullName: 'Nom Complet',
    enterYourFullName: 'Entrez votre nom complet',
    createAPassword: 'Créez un mot de passe',
    confirmPassword: 'Confirmer le Mot de Passe',
    confirmYourPassword: 'Confirmez votre mot de passe',
    iAgreeTo: 'J\'accepte les',
    termsOfService: 'Conditions de Service',
    creatingAccount: 'Création du Compte...',
    createAccountButton: 'Créer un Compte',
    becomeASeller: 'Devenir Vendeur',
    joinZizlaAndStartSelling: 'Rejoignez Zizla et commencez à vendre vos produits à des milliers de clients',
    signInToExistingSeller: 'Connectez-vous à votre compte vendeur existant et accédez à votre tableau de bord',
    newToSelling: 'Nouveau dans la vente?',
    createSellerAccount: 'Créez votre compte vendeur en seulement 5 étapes simples et commencez à vendre aujourd\'hui',
    getStarted: 'Commencer',
    whyChooseZizla: 'Pourquoi choisir Zizla pour vendre?',
    quickSetup: 'Configuration Rapide',
    getStartedInMinutes: 'Commencez en quelques minutes avec notre processus d\'inscription simple',
    lowFees: 'Frais Bas',
    competitiveCommissionRates: 'Taux de commission compétitifs pour maximiser vos profits',
    support247: 'Support 24/7',
    roundTheClockAssistance: 'Assistance 24h/24 pour tous vos besoins de vente',
    analytics: 'Analyses',
    detailedInsights: 'Informations détaillées pour développer votre entreprise',
  },
  German: {
    shop: 'Einkaufen',
    cart: 'Warenkorb',
    wishlist: 'Wunschliste',
    login: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    profile: 'Mein Profil',
    orders: 'Meine Bestellungen',
    search: 'Suchen...',
    all: 'Alle',
    home: 'Startseite',
    privacyPolicy: 'Datenschutzrichtlinie',
    getSupport: 'Support erhalten',
    submit: 'Absenden',
    tellYourQuery: 'Teilen Sie uns Ihre Anfrage mit',
    describeIssue: 'Beschreiben Sie Ihr Problem oder Ihre Frage hier...',
    submitQuery: 'Senden Sie Ihre Anfrage oder kontaktieren Sie uns direkt auf WhatsApp',
    contactOnWhatsApp: 'Auf WhatsApp kontaktieren',
    welcome: 'Willkommen bei Zizla',
    description: 'Ihr ultimatives Ziel für die neuesten und intelligentesten Gadgets. Von Smartphones und Smartwatches bis hin zu wichtigen Accessoires bringen wir Ihnen das Beste in Innovation - alles an einem Ort.',
    copyright: 'Copyright 2025 © Zizla Alle Rechte vorbehalten.',
    featuredProducts: 'EMPFOHLENE PRODUKTE',
    viewAllProducts: 'Alle Produkte anzeigen',
    website: 'WEBSITE?',
    contact: 'KONTAKT',
    news: 'NEUIGKEITEN',
    freeShipping: 'Kostenloser Versand über 150 $!',
    startsFrom: 'Ab',
    learnMore: 'MEHR ERFAHREN',
    zizlaYoullLove: 'Zizla, das Sie lieben werden. Preise, denen Sie vertrauen können.',
    setLanguageCurrency: 'Sprache und Währung festlegen',
    setLanguage: 'Sprache festlegen',
    selectPreferred: 'Wählen Sie Ihre bevorzugte Sprache und Währung. Sie können die Einstellungen jederzeit aktualisieren.',
    selectLanguagePreferred: 'Wählen Sie Ihre bevorzugte Sprache. Sie können die Einstellungen jederzeit aktualisieren.',
    language: 'Sprache',
    currency: 'Währung',
    save: 'Speichern',
    loginRegister: 'Anmelden / Registrieren',
    becomeSeller: 'Verkäufer werden',
    loginAsSeller: 'Als Verkäufer anmelden',
    areYouSeller: 'Sind Sie ein Verkäufer?',
    dontHaveAccount: 'Haben Sie kein Konto?',
    signUp: 'Registrieren',
    continueWith: 'Oder fortfahren mit',
    continueWithGoogle: 'Mit Google fortfahren',
    continueWithFacebook: 'Mit Facebook fortfahren',
    continueWithEmail: 'Mit E-Mail fortfahren',
    welcomeBack: 'Willkommen Zurück',
    signInToAccount: 'Melden Sie sich bei Ihrem Zizla-Konto an',
    backToHome: 'Zurück zur Startseite',
    demoCredentials: 'Demo-Anmeldedaten',
    useTheseCredentials: 'Verwenden Sie diese Anmeldedaten zum Anmelden:',
    fillDemoCredentials: 'Demo-Anmeldedaten Ausfüllen',
    emailAddress: 'E-Mail-Adresse',
    enterYourEmail: 'Geben Sie Ihre E-Mail ein',
    enterYourPassword: 'Geben Sie Ihr Passwort ein',
    rememberMe: 'Angemeldet bleiben',
    forgotPassword: 'Passwort vergessen?',
    signingIn: 'Anmeldung läuft...',
    signIn: 'Anmelden',
    alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
    createAccount: 'Konto Erstellen',
    joinZizla: 'Treten Sie Zizla bei und beginnen Sie mit dem Einkaufen',
    fullName: 'Vollständiger Name',
    enterYourFullName: 'Geben Sie Ihren vollständigen Namen ein',
    createAPassword: 'Erstellen Sie ein Passwort',
    confirmPassword: 'Passwort Bestätigen',
    confirmYourPassword: 'Bestätigen Sie Ihr Passwort',
    iAgreeTo: 'Ich stimme den',
    termsOfService: 'Nutzungsbedingungen',
    creatingAccount: 'Konto wird erstellt...',
    createAccountButton: 'Konto Erstellen',
    becomeASeller: 'Verkäufer Werden',
    joinZizlaAndStartSelling: 'Treten Sie Zizla bei und beginnen Sie, Ihre Produkte an Tausende von Kunden zu verkaufen',
    signInToExistingSeller: 'Melden Sie sich bei Ihrem bestehenden Verkäuferkonto an und greifen Sie auf Ihr Dashboard zu',
    newToSelling: 'Neu im Verkauf?',
    createSellerAccount: 'Erstellen Sie Ihr Verkäuferkonto in nur 5 einfachen Schritten und beginnen Sie noch heute mit dem Verkauf',
    getStarted: 'Loslegen',
    whyChooseZizla: 'Warum Zizla zum Verkaufen wählen?',
    quickSetup: 'Schnelle Einrichtung',
    getStartedInMinutes: 'Beginnen Sie in wenigen Minuten mit unserem einfachen Registrierungsprozess',
    lowFees: 'Niedrige Gebühren',
    competitiveCommissionRates: 'Wettbewerbsfähige Provisionssätze, um Ihre Gewinne zu maximieren',
    support247: '24/7 Support',
    roundTheClockAssistance: 'Rund um die Uhr Unterstützung für alle Ihre Verkaufsanforderungen',
    analytics: 'Analysen',
    detailedInsights: 'Detaillierte Einblicke, um Ihr Geschäft zu entwickeln',
  },
  Italian: {
    shop: 'Negozio',
    cart: 'Carrello',
    wishlist: 'Lista dei desideri',
    login: 'Accedi',
    register: 'Registrati',
    logout: 'Esci',
    profile: 'Il Mio Profilo',
    orders: 'I Miei Ordini',
    search: 'Cerca...',
    all: 'Tutti',
    home: 'Home',
    privacyPolicy: 'Informativa sulla Privacy',
    getSupport: 'Ottieni Supporto',
    submit: 'Invia',
    tellYourQuery: 'Raccontaci la tua richiesta',
    describeIssue: 'Descrivi il tuo problema o domanda qui...',
    submitQuery: 'Invia la tua richiesta o contattaci direttamente su WhatsApp',
    contactOnWhatsApp: 'Contatta su WhatsApp',
    welcome: 'Benvenuto su Zizla',
    description: 'la tua destinazione definitiva per i gadget più recenti e intelligenti. Dagli smartphone e smartwatch agli accessori essenziali, ti portiamo il meglio dell\'innovazione, tutto in un unico posto.',
    copyright: 'Copyright 2025 © Zizla Tutti i diritti riservati.',
    featuredProducts: 'PRODOTTI IN EVIDENZA',
    viewAllProducts: 'Visualizza Tutti i Prodotti',
    website: 'SITO WEB?',
    contact: 'CONTATTO',
    news: 'NOTIZIE',
    freeShipping: 'Spedizione Gratuita sopra $150!',
    startsFrom: 'A partire da',
    learnMore: 'SCOPRI DI PIÙ',
    zizlaYoullLove: 'Zizla che amerai. Prezzi di cui ti fiderai.',
    setLanguageCurrency: 'Imposta lingua e valuta',
    setLanguage: 'Imposta lingua',
    selectPreferred: 'Seleziona la tua lingua e valuta preferite. Puoi aggiornare le impostazioni in qualsiasi momento.',
    selectLanguagePreferred: 'Seleziona la tua lingua preferita. Puoi aggiornare le impostazioni in qualsiasi momento.',
    language: 'Lingua',
    currency: 'Valuta',
    save: 'Salva',
    loginRegister: 'Accedi / Registrati',
    becomeSeller: 'Diventa un Venditore',
    loginAsSeller: 'Accedi come venditore',
    areYouSeller: 'Sei un venditore?',
    dontHaveAccount: 'Non hai un account?',
    signUp: 'Registrati',
    continueWith: 'Oppure continua con',
    continueWithGoogle: 'Continua con Google',
    continueWithFacebook: 'Continua con Facebook',
    continueWithEmail: 'Continua con Email',
    welcomeBack: 'Bentornato',
    signInToAccount: 'Accedi al tuo account Zizla',
    backToHome: 'Torna alla Home',
    demoCredentials: 'Credenziali Demo',
    useTheseCredentials: 'Usa queste credenziali per accedere:',
    fillDemoCredentials: 'Compila Credenziali Demo',
    emailAddress: 'Indirizzo Email',
    enterYourEmail: 'Inserisci la tua email',
    enterYourPassword: 'Inserisci la tua password',
    rememberMe: 'Ricordami',
    forgotPassword: 'Password dimenticata?',
    signingIn: 'Accesso in corso...',
    signIn: 'Accedi',
    alreadyHaveAccount: 'Hai già un account?',
    createAccount: 'Crea Account',
    joinZizla: 'Unisciti a Zizla e inizia a fare acquisti',
    fullName: 'Nome Completo',
    enterYourFullName: 'Inserisci il tuo nome completo',
    createAPassword: 'Crea una password',
    confirmPassword: 'Conferma Password',
    confirmYourPassword: 'Conferma la tua password',
    iAgreeTo: 'Accetto i',
    termsOfService: 'Termini di Servizio',
    creatingAccount: 'Creazione Account...',
    createAccountButton: 'Crea Account',
    becomeASeller: 'Diventa un Venditore',
    joinZizlaAndStartSelling: 'Unisciti a Zizla e inizia a vendere i tuoi prodotti a migliaia di clienti',
    signInToExistingSeller: 'Accedi al tuo account venditore esistente e accedi alla tua dashboard',
    newToSelling: 'Nuovo alle vendite?',
    createSellerAccount: 'Crea il tuo account venditore in solo 5 semplici passaggi e inizia a vendere oggi',
    getStarted: 'Inizia',
    whyChooseZizla: 'Perché scegliere Zizla per vendere?',
    quickSetup: 'Configurazione Rapida',
    getStartedInMinutes: 'Inizia in pochi minuti con il nostro semplice processo di registrazione',
    lowFees: 'Tariffe Basse',
    competitiveCommissionRates: 'Tariffe di commissione competitive per massimizzare i tuoi profitti',
    support247: 'Supporto 24/7',
    roundTheClockAssistance: 'Assistenza 24 ore su 24 per tutte le tue esigenze di vendita',
    analytics: 'Analisi',
    detailedInsights: 'Informazioni dettagliate per far crescere la tua attività',
  },
  Portuguese: {
    shop: 'Loja',
    cart: 'Carrinho',
    wishlist: 'Lista de Desejos',
    login: 'Entrar',
    register: 'Registrar',
    logout: 'Sair',
    profile: 'Meu Perfil',
    orders: 'Meus Pedidos',
    search: 'Pesquisar...',
    all: 'Todos',
    home: 'Início',
    privacyPolicy: 'Política de Privacidade',
    getSupport: 'Obter Suporte',
    submit: 'Enviar',
    tellYourQuery: 'Conte-nos sua consulta',
    describeIssue: 'Descreva seu problema ou pergunta aqui...',
    submitQuery: 'Envie sua consulta ou entre em contato conosco diretamente no WhatsApp',
    contactOnWhatsApp: 'Contatar no WhatsApp',
    welcome: 'Bem-vindo ao Zizla',
    description: 'seu destino definitivo para os gadgets mais recentes e inteligentes. De smartphones e smartwatches a acessórios essenciais, trazemos o melhor em inovação - tudo em um só lugar.',
    copyright: 'Copyright 2025 © Zizla Todos os direitos reservados.',
    featuredProducts: 'PRODUTOS EM DESTAQUE',
    viewAllProducts: 'Ver Todos os Produtos',
    website: 'WEBSITE?',
    contact: 'CONTATO',
    news: 'NOTÍCIAS',
    freeShipping: 'Frete Grátis Acima de $150!',
    startsFrom: 'A partir de',
    learnMore: 'SAIBA MAIS',
    zizlaYoullLove: 'Zizla que você vai adorar. Preços em que você confiará.',
    setLanguageCurrency: 'Definir idioma e moeda',
    setLanguage: 'Definir idioma',
    selectPreferred: 'Selecione seu idioma e moeda preferidos. Você pode atualizar as configurações a qualquer momento.',
    selectLanguagePreferred: 'Selecione seu idioma preferido. Você pode atualizar as configurações a qualquer momento.',
    language: 'Idioma',
    currency: 'Moeda',
    save: 'Salvar',
    loginRegister: 'Entrar / Registrar',
    becomeSeller: 'Tornar-se Vendedor',
    loginAsSeller: 'Entrar como vendedor',
    areYouSeller: 'Você é um vendedor?',
    dontHaveAccount: 'Não tem uma conta?',
    signUp: 'Inscrever-se',
    continueWith: 'Ou continuar com',
    continueWithGoogle: 'Continuar com Google',
    continueWithFacebook: 'Continuar com Facebook',
    continueWithEmail: 'Continuar com Email',
    welcomeBack: 'Bem-vindo de Volta',
    signInToAccount: 'Entre na sua conta Zizla',
    backToHome: 'Voltar para Início',
    demoCredentials: 'Credenciais de Demonstração',
    useTheseCredentials: 'Use estas credenciais para fazer login:',
    fillDemoCredentials: 'Preencher Credenciais de Demonstração',
    emailAddress: 'Endereço de E-mail',
    enterYourEmail: 'Digite seu e-mail',
    enterYourPassword: 'Digite sua senha',
    rememberMe: 'Lembrar-me',
    forgotPassword: 'Esqueceu a senha?',
    signingIn: 'Entrando...',
    signIn: 'Entrar',
    alreadyHaveAccount: 'Já tem uma conta?',
    createAccount: 'Criar Conta',
    joinZizla: 'Junte-se ao Zizla e comece a comprar',
    fullName: 'Nome Completo',
    enterYourFullName: 'Digite seu nome completo',
    createAPassword: 'Crie uma senha',
    confirmPassword: 'Confirmar Senha',
    confirmYourPassword: 'Confirme sua senha',
    iAgreeTo: 'Eu concordo com os',
    termsOfService: 'Termos de Serviço',
    creatingAccount: 'Criando Conta...',
    createAccountButton: 'Criar Conta',
    becomeASeller: 'Tornar-se Vendedor',
    joinZizlaAndStartSelling: 'Junte-se ao Zizla e comece a vender seus produtos para milhares de clientes',
    signInToExistingSeller: 'Entre na sua conta de vendedor existente e acesse seu painel',
    newToSelling: 'Novo em vendas?',
    createSellerAccount: 'Crie sua conta de vendedor em apenas 5 passos simples e comece a vender hoje',
    getStarted: 'Começar',
    whyChooseZizla: 'Por que escolher Zizla para vender?',
    quickSetup: 'Configuração Rápida',
    getStartedInMinutes: 'Comece em minutos com nosso processo de registro simples',
    lowFees: 'Taxas Baixas',
    competitiveCommissionRates: 'Taxas de comissão competitivas para maximizar seus lucros',
    support247: 'Suporte 24/7',
    roundTheClockAssistance: 'Assistência 24 horas para todas as suas necessidades de venda',
    analytics: 'Análises',
    detailedInsights: 'Informações detalhadas para fazer crescer seu negócio',
  },
  Chinese: {
    shop: '商店',
    cart: '购物车',
    wishlist: '愿望清单',
    login: '登录',
    register: '注册',
    logout: '登出',
    profile: '我的资料',
    orders: '我的订单',
    search: '搜索...',
    all: '全部',
    home: '首页',
    privacyPolicy: '隐私政策',
    getSupport: '获取支持',
    submit: '提交',
    tellYourQuery: '告诉我们您的查询',
    describeIssue: '在此描述您的问题或疑问...',
    submitQuery: '提交您的查询或直接在 WhatsApp 上联系我们',
    contactOnWhatsApp: '在 WhatsApp 上联系',
    welcome: '欢迎来到 Zizla',
    description: '您购买最新和最智能小工具的首选目的地。从智能手机和智能手表到基本配件，我们为您带来最好的创新 - 一切尽在一处。',
    copyright: '版权所有 2025 © Zizla 保留所有权利。',
    featuredProducts: '特色产品',
    viewAllProducts: '查看所有产品',
    website: '网站?',
    contact: '联系方式',
    news: '新闻',
    freeShipping: '超过 $150 免费送货！',
    startsFrom: '起价',
    learnMore: '了解更多',
    zizlaYoullLove: '您会喜欢的 Zizla。您会信任的价格。',
    setLanguageCurrency: '设置语言和货币',
    setLanguage: '设置语言',
    selectPreferred: '选择您首选的语言和货币。您可以随时更新设置。',
    selectLanguagePreferred: '选择您首选的语言。您可以随时更新设置。',
    language: '语言',
    currency: '货币',
    save: '保存',
    loginRegister: '登录 / 注册',
    becomeSeller: '成为卖家',
    loginAsSeller: '以卖家身份登录',
    areYouSeller: '您是卖家吗？',
    dontHaveAccount: '没有账户？',
    signUp: '注册',
    continueWith: '或继续使用',
    continueWithGoogle: '使用 Google 继续',
    continueWithFacebook: '使用 Facebook 继续',
    continueWithEmail: '使用 Email 继续',
    welcomeBack: '欢迎回来',
    signInToAccount: '登录您的 Zizla 账户',
    backToHome: '返回首页',
    demoCredentials: '演示凭据',
    useTheseCredentials: '使用以下凭据登录:',
    fillDemoCredentials: '填充演示凭据',
    emailAddress: '电子邮件地址',
    enterYourEmail: '输入您的电子邮件',
    enterYourPassword: '输入您的密码',
    rememberMe: '记住我',
    forgotPassword: '忘记密码?',
    signingIn: '正在登录...',
    signIn: '登录',
    alreadyHaveAccount: '已有账户?',
    createAccount: '创建账户',
    joinZizla: '加入 Zizla 并开始购物',
    fullName: '全名',
    enterYourFullName: '输入您的全名',
    createAPassword: '创建密码',
    confirmPassword: '确认密码',
    confirmYourPassword: '确认您的密码',
    iAgreeTo: '我同意',
    termsOfService: '服务条款',
    creatingAccount: '正在创建账户...',
    createAccountButton: '创建账户',
    becomeASeller: '成为卖家',
    joinZizlaAndStartSelling: '加入 Zizla，开始向数千名客户销售您的产品',
    signInToExistingSeller: '登录您现有的卖家账户并访问您的仪表板',
    newToSelling: '刚接触销售?',
    createSellerAccount: '只需5个简单步骤即可创建您的卖家账户，今天就开始销售',
    getStarted: '开始',
    whyChooseZizla: '为什么选择 Zizla 进行销售?',
    quickSetup: '快速设置',
    getStartedInMinutes: '通过我们简单的注册流程，几分钟内即可开始',
    lowFees: '低费用',
    competitiveCommissionRates: '具有竞争力的佣金率，最大化您的利润',
    support247: '24/7 支持',
    roundTheClockAssistance: '全天候协助满足您的所有销售需求',
    analytics: '分析',
    detailedInsights: '详细的见解以发展您的业务',
  },
  Japanese: {
    shop: 'ショップ',
    cart: 'カート',
    wishlist: 'ウィッシュリスト',
    login: 'ログイン',
    register: '登録',
    logout: 'ログアウト',
    profile: 'マイプロフィール',
    orders: 'マイ注文',
    search: '検索...',
    all: 'すべて',
    home: 'ホーム',
    privacyPolicy: 'プライバシーポリシー',
    getSupport: 'サポートを受ける',
    submit: '送信',
    tellYourQuery: 'お問い合わせを教えてください',
    describeIssue: '問題や質問をここに記述してください...',
    submitQuery: 'お問い合わせを送信するか、WhatsAppで直接お問い合わせください',
    contactOnWhatsApp: 'WhatsAppで連絡',
    welcome: 'Zizlaへようこそ',
    description: '最新で最もスマートなガジェットの究極の目的地。スマートフォンやスマートウォッチから必須のアクセサリーまで、イノベーションの最高のものを1つの場所でお届けします。',
    copyright: 'Copyright 2025 © Zizla 全著作権所有。',
    featuredProducts: 'おすすめ商品',
    viewAllProducts: 'すべての商品を見る',
    website: 'ウェブサイト?',
    contact: 'お問い合わせ',
    news: 'ニュース',
    freeShipping: '$150以上で送料無料！',
    startsFrom: 'から',
    learnMore: 'もっと見る',
    zizlaYoullLove: 'あなたが愛するZizla。信頼できる価格。',
    setLanguageCurrency: '言語と通貨を設定',
    setLanguage: '言語を設定',
    selectPreferred: '希望する言語と通貨を選択してください。設定はいつでも更新できます。',
    selectLanguagePreferred: '希望する言語を選択してください。設定はいつでも更新できます。',
    language: '言語',
    currency: '通貨',
    save: '保存',
    loginRegister: 'ログイン / 登録',
    becomeSeller: '販売者になる',
    loginAsSeller: '販売者としてログイン',
    areYouSeller: '販売者ですか？',
    dontHaveAccount: 'アカウントをお持ちでないですか？',
    signUp: '登録',
    continueWith: 'または次で続行',
    continueWithGoogle: 'Googleで続行',
    continueWithFacebook: 'Facebookで続行',
    continueWithEmail: 'Emailで続行',
    welcomeBack: 'おかえりなさい',
    signInToAccount: 'Zizlaアカウントにログイン',
    backToHome: 'ホームに戻る',
    demoCredentials: 'デモ認証情報',
    useTheseCredentials: 'これらの認証情報でログイン:',
    fillDemoCredentials: 'デモ認証情報を入力',
    emailAddress: 'メールアドレス',
    enterYourEmail: 'メールアドレスを入力',
    enterYourPassword: 'パスワードを入力',
    rememberMe: 'ログイン状態を保持',
    forgotPassword: 'パスワードをお忘れですか?',
    signingIn: 'ログイン中...',
    signIn: 'ログイン',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか?',
    createAccount: 'アカウント作成',
    joinZizla: 'Zizlaに参加してショッピングを始めましょう',
    fullName: 'フルネーム',
    enterYourFullName: 'フルネームを入力',
    createAPassword: 'パスワードを作成',
    confirmPassword: 'パスワード確認',
    confirmYourPassword: 'パスワードを確認',
    iAgreeTo: '同意します',
    termsOfService: '利用規約',
    creatingAccount: 'アカウント作成中...',
    createAccountButton: 'アカウント作成',
    becomeASeller: '販売者になる',
    joinZizlaAndStartSelling: 'Zizlaに参加して、何千人もの顧客に製品を販売し始めましょう',
    signInToExistingSeller: '既存の販売者アカウントにログインしてダッシュボードにアクセス',
    newToSelling: '販売は初めてですか?',
    createSellerAccount: 'わずか5つの簡単なステップで販売者アカウントを作成し、今日から販売を開始',
    getStarted: '始める',
    whyChooseZizla: '販売にZizlaを選ぶ理由は?',
    quickSetup: 'クイックセットアップ',
    getStartedInMinutes: 'シンプルな登録プロセスで数分で始められます',
    lowFees: '低手数料',
    competitiveCommissionRates: '利益を最大化する競争力のある手数料率',
    support247: '24/7サポート',
    roundTheClockAssistance: 'すべての販売ニーズに対応する24時間体制のサポート',
    analytics: '分析',
    detailedInsights: 'ビジネスを成長させるための詳細な洞察',
  },
  Korean: {
    shop: '쇼핑',
    cart: '장바구니',
    wishlist: '위시리스트',
    login: '로그인',
    register: '회원가입',
    logout: '로그아웃',
    profile: '내 프로필',
    orders: '내 주문',
    search: '검색...',
    all: '전체',
    home: '홈',
    privacyPolicy: '개인정보 보호정책',
    getSupport: '지원 받기',
    submit: '제출',
    tellYourQuery: '문의사항을 알려주세요',
    describeIssue: '문제나 질문을 여기에 설명하세요...',
    submitQuery: '문의사항을 제출하거나 WhatsApp으로 직접 문의하세요',
    contactOnWhatsApp: 'WhatsApp으로 연락',
    welcome: 'Zizla에 오신 것을 환영합니다',
    description: '최신 및 가장 스마트한 가젯의 궁극적인 목적지. 스마트폰과 스마트워치부터 필수 액세서리까지, 혁신의 최고를 한 곳에서 제공합니다.',
    copyright: 'Copyright 2025 © Zizla 모든 권리 보유.',
    featuredProducts: '추천 제품',
    viewAllProducts: '모든 제품 보기',
    website: '웹사이트?',
    contact: '연락처',
    news: '뉴스',
    freeShipping: '$150 이상 무료 배송!',
    startsFrom: '시작가',
    learnMore: '더 알아보기',
    zizlaYoullLove: '당신이 사랑할 Zizla. 신뢰할 수 있는 가격.',
    setLanguageCurrency: '언어 및 통화 설정',
    setLanguage: '언어 설정',
    selectPreferred: '선호하는 언어와 통화를 선택하세요. 설정은 언제든지 업데이트할 수 있습니다.',
    selectLanguagePreferred: '선호하는 언어를 선택하세요. 설정은 언제든지 업데이트할 수 있습니다.',
    language: '언어',
    currency: '통화',
    save: '저장',
    loginRegister: '로그인 / 회원가입',
    becomeSeller: '판매자 되기',
    loginAsSeller: '판매자로 로그인',
    areYouSeller: '판매자이신가요?',
    dontHaveAccount: '계정이 없으신가요?',
    signUp: '가입',
    continueWith: '또는 다음으로 계속',
    continueWithGoogle: 'Google로 계속',
    continueWithFacebook: 'Facebook으로 계속',
    continueWithEmail: 'Email로 계속',
    welcomeBack: '다시 오신 것을 환영합니다',
    signInToAccount: 'Zizla 계정에 로그인',
    backToHome: '홈으로 돌아가기',
    demoCredentials: '데모 자격 증명',
    useTheseCredentials: '다음 자격 증명으로 로그인:',
    fillDemoCredentials: '데모 자격 증명 채우기',
    emailAddress: '이메일 주소',
    enterYourEmail: '이메일을 입력하세요',
    enterYourPassword: '비밀번호를 입력하세요',
    rememberMe: '로그인 상태 유지',
    forgotPassword: '비밀번호를 잊으셨나요?',
    signingIn: '로그인 중...',
    signIn: '로그인',
    alreadyHaveAccount: '이미 계정이 있으신가요?',
    createAccount: '계정 만들기',
    joinZizla: 'Zizla에 가입하고 쇼핑을 시작하세요',
    fullName: '전체 이름',
    enterYourFullName: '전체 이름을 입력하세요',
    createAPassword: '비밀번호 만들기',
    confirmPassword: '비밀번호 확인',
    confirmYourPassword: '비밀번호를 확인하세요',
    iAgreeTo: '동의합니다',
    termsOfService: '서비스 약관',
    creatingAccount: '계정 생성 중...',
    createAccountButton: '계정 만들기',
    becomeASeller: '판매자 되기',
    joinZizlaAndStartSelling: 'Zizla에 가입하고 수천 명의 고객에게 제품을 판매하기 시작하세요',
    signInToExistingSeller: '기존 판매자 계정에 로그인하고 대시보드에 액세스',
    newToSelling: '판매가 처음이신가요?',
    createSellerAccount: '간단한 5단계로 판매자 계정을 만들고 오늘부터 판매를 시작하세요',
    getStarted: '시작하기',
    whyChooseZizla: '판매에 Zizla를 선택하는 이유는?',
    quickSetup: '빠른 설정',
    getStartedInMinutes: '간단한 등록 프로세스로 몇 분 안에 시작할 수 있습니다',
    lowFees: '낮은 수수료',
    competitiveCommissionRates: '수익을 극대화하는 경쟁력 있는 수수료율',
    support247: '24/7 지원',
    roundTheClockAssistance: '모든 판매 요구 사항에 대한 24시간 지원',
    analytics: '분석',
    detailedInsights: '비즈니스를 성장시키기 위한 상세한 인사이트',
  },
  Arabic: {
    shop: 'المتجر',
    cart: 'السلة',
    wishlist: 'قائمة الأمنيات',
    login: 'تسجيل الدخول',
    register: 'التسجيل',
    logout: 'تسجيل الخروج',
    profile: 'ملفي الشخصي',
    orders: 'طلباتي',
    search: 'بحث...',
    all: 'الكل',
    home: 'الرئيسية',
    privacyPolicy: 'سياسة الخصوصية',
    getSupport: 'الحصول على الدعم',
    submit: 'إرسال',
    tellYourQuery: 'أخبرنا باستفسارك',
    describeIssue: 'اوصف مشكلتك أو سؤالك هنا...',
    submitQuery: 'أرسل استفسارك أو اتصل بنا مباشرة على WhatsApp',
    contactOnWhatsApp: 'اتصل على WhatsApp',
    welcome: 'مرحباً بك في Zizla',
    description: 'وجهتك النهائية لأحدث وأذكى الأجهزة. من الهواتف الذكية والساعات الذكية إلى الملحقات الأساسية، نقدم لك الأفضل في الابتكار - كل ذلك في مكان واحد.',
    copyright: 'حقوق النشر 2025 © Zizla جميع الحقوق محفوظة.',
    featuredProducts: 'المنتجات المميزة',
    viewAllProducts: 'عرض جميع المنتجات',
    website: 'الموقع؟',
    contact: 'اتصل بنا',
    news: 'الأخبار',
    freeShipping: 'شحن مجاني لأكثر من 150 دولاراً!',
    startsFrom: 'يبدأ من',
    learnMore: 'اعرف المزيد',
    zizlaYoullLove: 'Zizla الذي ستحبه. أسعار ستثق بها.',
    setLanguageCurrency: 'تعيين اللغة والعملة',
    setLanguage: 'تعيين اللغة',
    selectPreferred: 'اختر لغتك وعملتك المفضلة. يمكنك تحديث الإعدادات في أي وقت.',
    selectLanguagePreferred: 'اختر لغتك المفضلة. يمكنك تحديث الإعدادات في أي وقت.',
    language: 'اللغة',
    currency: 'العملة',
    save: 'حفظ',
    loginRegister: 'تسجيل الدخول / التسجيل',
    becomeSeller: 'كن بائعاً',
    loginAsSeller: 'تسجيل الدخول كبائع',
    areYouSeller: 'هل أنت بائع؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    signUp: 'سجل',
    continueWith: 'أو المتابعة مع',
    continueWithGoogle: 'المتابعة مع Google',
    continueWithFacebook: 'المتابعة مع Facebook',
    continueWithEmail: 'المتابعة مع Email',
    welcomeBack: 'مرحباً بعودتك',
    signInToAccount: 'تسجيل الدخول إلى حساب Zizla الخاص بك',
    backToHome: 'العودة إلى الصفحة الرئيسية',
    demoCredentials: 'بيانات الاعتماد التجريبية',
    useTheseCredentials: 'استخدم بيانات الاعتماد هذه لتسجيل الدخول:',
    fillDemoCredentials: 'ملء بيانات الاعتماد التجريبية',
    emailAddress: 'عنوان البريد الإلكتروني',
    enterYourEmail: 'أدخل بريدك الإلكتروني',
    enterYourPassword: 'أدخل كلمة المرور',
    rememberMe: 'تذكرني',
    forgotPassword: 'نسيت كلمة المرور?',
    signingIn: 'جارٍ تسجيل الدخول...',
    signIn: 'تسجيل الدخول',
    alreadyHaveAccount: 'لديك حساب بالفعل?',
    createAccount: 'إنشاء حساب',
    joinZizla: 'انضم إلى Zizla وابدأ التسوق',
    fullName: 'الاسم الكامل',
    enterYourFullName: 'أدخل اسمك الكامل',
    createAPassword: 'إنشاء كلمة مرور',
    confirmPassword: 'تأكيد كلمة المرور',
    confirmYourPassword: 'تأكيد كلمة المرور',
    iAgreeTo: 'أوافق على',
    termsOfService: 'شروط الخدمة',
    creatingAccount: 'جارٍ إنشاء الحساب...',
    createAccountButton: 'إنشاء حساب',
    becomeASeller: 'كن بائعاً',
    joinZizlaAndStartSelling: 'انضم إلى Zizla وابدأ بيع منتجاتك لآلاف العملاء',
    signInToExistingSeller: 'تسجيل الدخول إلى حساب البائع الموجود والوصول إلى لوحة التحكم',
    newToSelling: 'جديد في البيع?',
    createSellerAccount: 'أنشئ حساب البائع الخاص بك في 5 خطوات بسيطة فقط وابدأ البيع اليوم',
    getStarted: 'ابدأ',
    whyChooseZizla: 'لماذا تختار Zizla للبيع?',
    quickSetup: 'إعداد سريع',
    getStartedInMinutes: 'ابدأ في دقائق مع عملية التسجيل البسيطة لدينا',
    lowFees: 'رسوم منخفضة',
    competitiveCommissionRates: 'معدلات عمولة تنافسية لتعظيم أرباحك',
    support247: 'دعم 24/7',
    roundTheClockAssistance: 'مساعدة على مدار الساعة لجميع احتياجات البيع الخاصة بك',
    analytics: 'التحليلات',
    detailedInsights: 'رؤى مفصلة لتنمية عملك',
  },
  Hindi: {
    shop: 'दुकान',
    cart: 'कार्ट',
    wishlist: 'इच्छा सूची',
    login: 'लॉगिन',
    register: 'रजिस्टर',
    logout: 'लॉगआउट',
    profile: 'मेरी प्रोफ़ाइल',
    orders: 'मेरे ऑर्डर',
    search: 'खोजें...',
    all: 'सभी',
    home: 'होम',
    privacyPolicy: 'गोपनीयता नीति',
    getSupport: 'सहायता प्राप्त करें',
    submit: 'सबमिट करें',
    tellYourQuery: 'अपनी क्वेरी बताएं',
    describeIssue: 'अपनी समस्या या प्रश्न यहाँ वर्णन करें...',
    submitQuery: 'अपनी क्वेरी सबमिट करें या WhatsApp पर सीधे संपर्क करें',
    contactOnWhatsApp: 'WhatsApp पर संपर्क करें',
    welcome: 'Zizla में आपका स्वागत है',
    description: 'नवीनतम और सबसे स्मार्ट गैजेट्स के लिए आपका अंतिम गंतव्य। स्मार्टफोन और स्मार्टवॉच से लेकर आवश्यक सामान तक, हम आपके लिए नवाचार में सर्वश्रेष्ठ लाते हैं - सब कुछ एक जगह पर।',
    copyright: 'कॉपीराइट 2025 © Zizla सभी अधिकार सुरक्षित।',
    featuredProducts: 'विशेष उत्पाद',
    viewAllProducts: 'सभी उत्पाद देखें',
    website: 'वेबसाइट?',
    contact: 'संपर्क',
    news: 'समाचार',
    freeShipping: '$150 से अधिक पर मुफ्त शिपिंग!',
    startsFrom: 'शुरू होता है',
    learnMore: 'और जानें',
    zizlaYoullLove: 'Zizla जिसे आप पसंद करेंगे। कीमतें जिन पर आप भरोसा करेंगे।',
    setLanguageCurrency: 'भाषा और मुद्रा सेट करें',
    setLanguage: 'भाषा सेट करें',
    selectPreferred: 'अपनी पसंदीदा भाषा और मुद्रा चुनें। आप किसी भी समय सेटिंग्स अपडेट कर सकते हैं।',
    selectLanguagePreferred: 'अपनी पसंदीदा भाषा चुनें। आप किसी भी समय सेटिंग्स अपडेट कर सकते हैं।',
    language: 'भाषा',
    currency: 'मुद्रा',
    save: 'सहेजें',
    loginRegister: 'लॉगिन / रजिस्टर',
    becomeSeller: 'विक्रेता बनें',
    loginAsSeller: 'विक्रेता के रूप में लॉगिन करें',
    areYouSeller: 'क्या आप एक विक्रेता हैं?',
    dontHaveAccount: 'खाता नहीं है?',
    signUp: 'साइन अप करें',
    continueWith: 'या इसके साथ जारी रखें',
    continueWithGoogle: 'Google के साथ जारी रखें',
    continueWithFacebook: 'Facebook के साथ जारी रखें',
    continueWithEmail: 'Email के साथ जारी रखें',
    welcomeBack: 'वापसी पर स्वागत है',
    signInToAccount: 'अपने Zizla खाते में साइन इन करें',
    backToHome: 'होम पर वापस जाएं',
    demoCredentials: 'डेमो क्रेडेंशियल',
    useTheseCredentials: 'लॉगिन करने के लिए इन क्रेडेंशियल का उपयोग करें:',
    fillDemoCredentials: 'डेमो क्रेडेंशियल भरें',
    emailAddress: 'ईमेल पता',
    enterYourEmail: 'अपना ईमेल दर्ज करें',
    enterYourPassword: 'अपना पासवर्ड दर्ज करें',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    signingIn: 'साइन इन हो रहा है...',
    signIn: 'साइन इन',
    alreadyHaveAccount: 'पहले से खाता है?',
    createAccount: 'खाता बनाएं',
    joinZizla: 'Zizla में शामिल हों और खरीदारी शुरू करें',
    fullName: 'पूरा नाम',
    enterYourFullName: 'अपना पूरा नाम दर्ज करें',
    createAPassword: 'एक पासवर्ड बनाएं',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    confirmYourPassword: 'अपने पासवर्ड की पुष्टि करें',
    iAgreeTo: 'मैं सहमत हूं',
    termsOfService: 'सेवा की शर्तें',
    creatingAccount: 'खाता बनाया जा रहा है...',
    createAccountButton: 'खाता बनाएं',
    becomeASeller: 'विक्रेता बनें',
    joinZizlaAndStartSelling: 'Zizla में शामिल हों और हजारों ग्राहकों को अपने उत्पाद बेचना शुरू करें',
    signInToExistingSeller: 'अपने मौजूदा विक्रेता खाते में साइन इन करें और अपने डैशबोर्ड तक पहुंचें',
    newToSelling: 'बिक्री में नए?',
    createSellerAccount: 'केवल 5 सरल चरणों में अपना विक्रेता खाता बनाएं और आज ही बेचना शुरू करें',
    getStarted: 'शुरू करें',
    whyChooseZizla: 'बिक्री के लिए Zizla क्यों चुनें?',
    quickSetup: 'त्वरित सेटअप',
    getStartedInMinutes: 'हमारी सरल पंजीकरण प्रक्रिया के साथ मिनटों में शुरू करें',
    lowFees: 'कम शुल्क',
    competitiveCommissionRates: 'अपने मुनाफे को अधिकतम करने के लिए प्रतिस्पर्धी कमीशन दरें',
    support247: '24/7 सहायता',
    roundTheClockAssistance: 'आपकी सभी बिक्री आवश्यकताओं के लिए चौबीसों घंटे सहायता',
    analytics: 'विश्लेषण',
    detailedInsights: 'अपने व्यवसाय को बढ़ाने के लिए विस्तृत अंतर्दृष्टि',
  },
  Urdu: {
    shop: 'دکان',
    cart: 'کارٹ',
    wishlist: 'خواہشات کی فہرست',
    login: 'لاگ ان',
    register: 'رجسٹر',
    logout: 'لاگ آؤٹ',
    profile: 'میری پروفائل',
    orders: 'میرے آرڈرز',
    search: 'تلاش کریں...',
    all: 'سب',
    home: 'ہوم',
    privacyPolicy: 'رازداری کی پالیسی',
    getSupport: 'مدد حاصل کریں',
    submit: 'جمع کروائیں',
    tellYourQuery: 'اپنا سوال بتائیں',
    describeIssue: 'اپنا مسئلہ یا سوال یہاں بیان کریں...',
    submitQuery: 'اپنا سوال جمع کروائیں یا WhatsApp پر براہ راست رابطہ کریں',
    contactOnWhatsApp: 'WhatsApp پر رابطہ کریں',
    welcome: 'Zizla میں خوش آمدید',
    description: 'تازہ ترین اور سب سے ہوشیار گیجٹس کے لیے آپ کا حتمی مقام۔ اسمارٹ فونز اور اسمارٹ واچ سے لے کر ضروری لوازمات تک، ہم آپ کے لیے جدت میں بہترین لاتے ہیں - سب کچھ ایک جگہ پر۔',
    copyright: 'کاپی رائٹ 2025 © Zizla تمام حقوق محفوظ ہیں۔',
    featuredProducts: 'نمایاں مصنوعات',
    viewAllProducts: 'تمام مصنوعات دیکھیں',
    website: 'ویب سائٹ؟',
    contact: 'رابطہ',
    news: 'خبریں',
    freeShipping: '$150 سے زیادہ پر مفت شپنگ!',
    startsFrom: 'شروع ہوتا ہے',
    learnMore: 'مزید جانیں',
    zizlaYoullLove: 'Zizla جسے آپ پسند کریں گے۔ قیمتیں جن پر آپ بھروسہ کریں گے۔',
    setLanguageCurrency: 'زبان اور کرنسی سیٹ کریں',
    setLanguage: 'زبان سیٹ کریں',
    selectPreferred: 'اپنی پسندیدہ زبان اور کرنسی منتخب کریں۔ آپ کسی بھی وقت ترتیبات اپ ڈیٹ کر سکتے ہیں۔',
    selectLanguagePreferred: 'اپنی پسندیدہ زبان منتخب کریں۔ آپ کسی بھی وقت ترتیبات اپ ڈیٹ کر سکتے ہیں۔',
    language: 'زبان',
    currency: 'کرنسی',
    save: 'محفوظ کریں',
    loginRegister: 'لاگ ان / رجسٹر',
    becomeSeller: 'فروش بنیں',
    loginAsSeller: 'فروش کے طور پر لاگ ان کریں',
    areYouSeller: 'کیا آپ ایک فروش ہیں؟',
    dontHaveAccount: 'اکاؤنٹ نہیں ہے؟',
    signUp: 'سائن اپ کریں',
    continueWith: 'یا اس کے ساتھ جاری رکھیں',
    continueWithGoogle: 'Google کے ساتھ جاری رکھیں',
    continueWithFacebook: 'Facebook کے ساتھ جاری رکھیں',
    continueWithEmail: 'Email کے ساتھ جاری رکھیں',
    welcomeBack: 'واپسی پر خوش آمدید',
    signInToAccount: 'اپنے Zizla اکاؤنٹ میں لاگ ان کریں',
    backToHome: 'ہوم پر واپس جائیں',
    demoCredentials: 'ڈیمو کریڈنشلز',
    useTheseCredentials: 'لاگ ان کرنے کے لیے ان کریڈنشلز کا استعمال کریں:',
    fillDemoCredentials: 'ڈیمو کریڈنشلز بھریں',
    emailAddress: 'ای میل پتا',
    enterYourEmail: 'اپنا ای میل درج کریں',
    enterYourPassword: 'اپنا پاس ورڈ درج کریں',
    rememberMe: 'مجھے یاد رکھیں',
    forgotPassword: 'پاس ورڈ بھول گئے?',
    signingIn: 'لاگ ان ہو رہا ہے...',
    signIn: 'لاگ ان',
    alreadyHaveAccount: 'پہلے سے اکاؤنٹ ہے?',
    createAccount: 'اکاؤنٹ بنائیں',
    joinZizla: 'Zizla میں شامل ہوں اور خریداری شروع کریں',
    fullName: 'پورا نام',
    enterYourFullName: 'اپنا پورا نام درج کریں',
    createAPassword: 'ایک پاس ورڈ بنائیں',
    confirmPassword: 'پاس ورڈ کی تصدیق کریں',
    confirmYourPassword: 'اپنے پاس ورڈ کی تصدیق کریں',
    iAgreeTo: 'میں راضی ہوں',
    termsOfService: 'سروس کی شرائط',
    creatingAccount: 'اکاؤنٹ بنایا جا رہا ہے...',
    createAccountButton: 'اکاؤنٹ بنائیں',
    becomeASeller: 'فروش بنیں',
    joinZizlaAndStartSelling: 'Zizla میں شامل ہوں اور ہزاروں گاہکوں کو اپنے مصنوعات بیچنا شروع کریں',
    signInToExistingSeller: 'اپنے موجودہ فروش اکاؤنٹ میں لاگ ان کریں اور اپنے ڈیش بورڈ تک رسائی حاصل کریں',
    newToSelling: 'فروخت میں نئے?',
    createSellerAccount: 'صرف 5 آسان مراحل میں اپنا فروش اکاؤنٹ بنائیں اور آج ہی بیچنا شروع کریں',
    getStarted: 'شروع کریں',
    whyChooseZizla: 'فروخت کے لیے Zizla کیوں منتخب کریں?',
    quickSetup: 'تیز ترتیب',
    getStartedInMinutes: 'ہمارے آسان رجسٹریشن عمل کے ساتھ منٹوں میں شروع کریں',
    lowFees: 'کم فیس',
    competitiveCommissionRates: 'اپنے منافع کو زیادہ سے زیادہ کرنے کے لیے مسابقتی کمیشن کی شرحیں',
    support247: '24/7 سپورٹ',
    roundTheClockAssistance: 'آپ کی تمام فروخت کی ضروریات کے لیے چوبیس گھنٹے مدد',
    analytics: 'تجزیات',
    detailedInsights: 'اپنے کاروبار کو بڑھانے کے لیے تفصیلی بصیرت',
  },
}

// Currency conversion rates (base: USD)
const currencyRates = {
  'USD - US Dollar': 1,
  'PKR - Pakistani Rupee': 278.5,
  'EUR - Euro': 0.92,
  'GBP - British Pound': 0.79,
  'INR - Indian Rupee': 83.12,
  'CNY - Chinese Yuan': 7.24,
  'JPY - Japanese Yen': 150.5,
  'AED - UAE Dirham': 3.67,
  'SAR - Saudi Riyal': 3.75,
  'BHD - Bahraini Dinar': 0.377,
  'KWD - Kuwaiti Dinar': 0.307,
  'QAR - Qatari Riyal': 3.64,
}

// Currency symbols
const currencySymbols = {
  'USD - US Dollar': '$',
  'PKR - Pakistani Rupee': 'Rs',
  'EUR - Euro': '€',
  'GBP - British Pound': '£',
  'INR - Indian Rupee': '₹',
  'CNY - Chinese Yuan': '¥',
  'JPY - Japanese Yen': '¥',
  'AED - UAE Dirham': 'د.إ',
  'SAR - Saudi Riyal': '﷼',
  'BHD - Bahraini Dinar': '.د.ب',
  'KWD - Kuwaiti Dinar': 'د.ك',
  'QAR - Qatari Riyal': '﷼',
}

export const LanguageCurrencyProvider = ({ children }) => {
  const [language, setLanguage] = useState('English')
  const [currency, setCurrency] = useState('PKR - Pakistani Rupee')

  useEffect(() => {
    // Load saved preferences
    const savedLanguage = localStorage.getItem('language')
    const savedCurrency = localStorage.getItem('currency')
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage)
    }
    if (savedCurrency && currencyRates[savedCurrency] !== undefined) {
      setCurrency(savedCurrency)
    }
  }, [])

  const t = (key) => {
    return translations[language]?.[key] || translations['English']?.[key] || key
  }

  const formatCurrency = (amount) => {
    const rate = currencyRates[currency] || 1
    const convertedAmount = amount * rate
    const symbol = currencySymbols[currency] || '$'
    
    // Format number based on currency
    if (currency === 'PKR - Pakistani Rupee' || currency === 'INR - Indian Rupee') {
      return `${symbol}${convertedAmount.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`
    }
    return `${symbol}${convertedAmount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  }

  const getCurrencySymbol = () => {
    return currencySymbols[currency] || '$'
  }

  const updateLanguage = (newLanguage) => {
    setLanguage(newLanguage)
    localStorage.setItem('language', newLanguage)
  }

  const updateCurrency = (newCurrency) => {
    setCurrency(newCurrency)
    localStorage.setItem('currency', newCurrency)
  }

  return (
    <LanguageCurrencyContext.Provider
      value={{
        language,
        currency,
        t,
        formatCurrency,
        getCurrencySymbol,
        updateLanguage,
        updateCurrency,
      }}
    >
      {children}
    </LanguageCurrencyContext.Provider>
  )
}

