// Mock data for Orders & Operations module

// Order Timeline Data with detailed status history
export const orderTimelineData = [
  {
    id: 'order-001',
    orderId: 'ORD-2024-001',
    status: 'SHIPPED',
    currentStage: 2, // 0: Placed, 1: Packed, 2: Shipped, 3: Delivered
    timeline: [
      {
        stage: 'placed',
        label: 'Order Placed',
        timestamp: '2024-01-15T10:30:00Z',
        completed: true,
      },
      {
        stage: 'packed',
        label: 'Packed',
        timestamp: '2024-01-15T14:20:00Z',
        completed: true,
      },
      {
        stage: 'shipped',
        label: 'Shipped',
        timestamp: '2024-01-16T09:15:00Z',
        completed: true,
      },
      {
        stage: 'delivered',
        label: 'Delivered',
        timestamp: null,
        completed: false,
        expectedDate: '2024-01-18T17:00:00Z',
      },
    ],
    buyer: 'John Doe',
    total: 1250.00,
    items: 3,
  },
  {
    id: 'order-002',
    orderId: 'ORD-2024-002',
    status: 'DELIVERED',
    currentStage: 3,
    timeline: [
      {
        stage: 'placed',
        label: 'Order Placed',
        timestamp: '2024-01-10T08:15:00Z',
        completed: true,
      },
      {
        stage: 'packed',
        label: 'Packed',
        timestamp: '2024-01-10T12:30:00Z',
        completed: true,
      },
      {
        stage: 'shipped',
        label: 'Shipped',
        timestamp: '2024-01-11T10:00:00Z',
        completed: true,
      },
      {
        stage: 'delivered',
        label: 'Delivered',
        timestamp: '2024-01-13T15:45:00Z',
        completed: true,
      },
    ],
    buyer: 'Jane Smith',
    total: 890.50,
    items: 2,
  },
  {
    id: 'order-003',
    orderId: 'ORD-2024-003',
    status: 'PENDING',
    currentStage: 0,
    timeline: [
      {
        stage: 'placed',
        label: 'Order Placed',
        timestamp: '2024-01-17T16:20:00Z',
        completed: true,
      },
      {
        stage: 'packed',
        label: 'Packed',
        timestamp: null,
        completed: false,
        expectedDate: '2024-01-18T12:00:00Z',
      },
      {
        stage: 'shipped',
        label: 'Shipped',
        timestamp: null,
        completed: false,
        expectedDate: '2024-01-19T10:00:00Z',
      },
      {
        stage: 'delivered',
        label: 'Delivered',
        timestamp: null,
        completed: false,
        expectedDate: '2024-01-21T17:00:00Z',
      },
    ],
    buyer: 'Mike Johnson',
    total: 450.00,
    items: 1,
  },
  {
    id: 'order-004',
    orderId: 'ORD-2024-004',
    status: 'PROCESSING',
    currentStage: 1,
    timeline: [
      {
        stage: 'placed',
        label: 'Order Placed',
        timestamp: '2024-01-16T11:00:00Z',
        completed: true,
      },
      {
        stage: 'packed',
        label: 'Packed',
        timestamp: '2024-01-17T09:30:00Z',
        completed: true,
      },
      {
        stage: 'shipped',
        label: 'Shipped',
        timestamp: null,
        completed: false,
        expectedDate: '2024-01-18T14:00:00Z',
      },
      {
        stage: 'delivered',
        label: 'Delivered',
        timestamp: null,
        completed: false,
        expectedDate: '2024-01-20T17:00:00Z',
      },
    ],
    buyer: 'Sarah Williams',
    total: 2100.75,
    items: 5,
  },
]

// Returns & Refunds Data
export const returnsRefundsData = [
  {
    id: 'return-001',
    orderId: 'ORD-2024-001',
    orderDate: '2024-01-10T08:15:00Z',
    returnRequestDate: '2024-01-14T10:30:00Z',
    buyer: 'John Doe',
    buyerEmail: 'john@example.com',
    items: [
      { name: 'Wireless Earbuds Pro', quantity: 1, price: 150.00 },
    ],
    totalAmount: 150.00,
    reason: 'Defective product - right earbud not working',
    reasonCategory: 'defective',
    status: 'pending',
    refundStatus: 'not_initiated',
    adminNotes: null,
    rejectionReason: null,
    approvedDate: null,
    rejectedDate: null,
    refundInitiatedDate: null,
    refundCompletedDate: null,
  },
  {
    id: 'return-002',
    orderId: 'ORD-2024-002',
    orderDate: '2024-01-08T14:20:00Z',
    returnRequestDate: '2024-01-12T09:15:00Z',
    buyer: 'Jane Smith',
    buyerEmail: 'jane@example.com',
    items: [
      { name: 'Designer T-Shirt', quantity: 1, price: 45.00 },
      { name: 'Jeans Classic', quantity: 1, price: 65.00 },
    ],
    totalAmount: 110.00,
    reason: 'Wrong size - ordered medium but received small',
    reasonCategory: 'wrong_size',
    status: 'approved',
    refundStatus: 'initiated',
    adminNotes: 'Customer confirmed wrong size, approved for return',
    rejectionReason: null,
    approvedDate: '2024-01-13T11:00:00Z',
    rejectedDate: null,
    refundInitiatedDate: '2024-01-13T11:30:00Z',
    refundCompletedDate: null,
  },
  {
    id: 'return-003',
    orderId: 'ORD-2024-003',
    orderDate: '2024-01-05T10:00:00Z',
    returnRequestDate: '2024-01-10T15:45:00Z',
    buyer: 'Mike Johnson',
    buyerEmail: 'mike@example.com',
    items: [
      { name: 'Smart Watch Series 9', quantity: 1, price: 299.99 },
    ],
    totalAmount: 299.99,
    reason: 'Changed my mind - no longer need the product',
    reasonCategory: 'change_of_mind',
    status: 'rejected',
    refundStatus: 'not_initiated',
    adminNotes: null,
    rejectionReason: 'Return request submitted after 7-day return window',
    approvedDate: null,
    rejectedDate: '2024-01-11T09:00:00Z',
    refundInitiatedDate: null,
    refundCompletedDate: null,
  },
  {
    id: 'return-004',
    orderId: 'ORD-2024-004',
    orderDate: '2024-01-03T12:30:00Z',
    returnRequestDate: '2024-01-08T11:20:00Z',
    buyer: 'Sarah Williams',
    buyerEmail: 'sarah@example.com',
    items: [
      { name: 'Kitchen Knife Set', quantity: 1, price: 89.99 },
    ],
    totalAmount: 89.99,
    reason: 'Product damaged during shipping',
    reasonCategory: 'damaged',
    status: 'approved',
    refundStatus: 'completed',
    adminNotes: 'Confirmed damage from shipping, full refund processed',
    rejectionReason: null,
    approvedDate: '2024-01-09T10:00:00Z',
    rejectedDate: null,
    refundInitiatedDate: '2024-01-09T10:15:00Z',
    refundCompletedDate: '2024-01-09T14:30:00Z',
  },
  {
    id: 'return-005',
    orderId: 'ORD-2024-005',
    orderDate: '2024-01-15T16:00:00Z',
    returnRequestDate: '2024-01-17T10:00:00Z',
    buyer: 'David Brown',
    buyerEmail: 'david@example.com',
    items: [
      { name: 'USB-C Fast Charger', quantity: 2, price: 25.00 },
    ],
    totalAmount: 50.00,
    reason: 'Not as described - charging speed is slower than advertised',
    reasonCategory: 'not_as_described',
    status: 'pending',
    refundStatus: 'not_initiated',
    adminNotes: null,
    rejectionReason: null,
    approvedDate: null,
    rejectedDate: null,
    refundInitiatedDate: null,
    refundCompletedDate: null,
  },
]

// Delayed Orders Data
export const delayedOrdersData = [
  {
    id: 'order-delayed-001',
    orderId: 'ORD-2024-006',
    buyer: 'Alice Cooper',
    buyerEmail: 'alice@example.com',
    orderDate: '2024-01-10T10:00:00Z',
    expectedDeliveryDate: '2024-01-15T17:00:00Z',
    currentDate: '2024-01-17T12:00:00Z',
    daysDelayed: 2,
    status: 'SHIPPED',
    currentLocation: 'In Transit - Distribution Center',
    courier: 'FastShip Express',
    trackingNumber: 'FS123456789',
    total: 350.00,
    items: 2,
    delayReason: 'Weather conditions',
  },
  {
    id: 'order-delayed-002',
    orderId: 'ORD-2024-007',
    buyer: 'Bob Wilson',
    buyerEmail: 'bob@example.com',
    orderDate: '2024-01-12T14:30:00Z',
    expectedDeliveryDate: '2024-01-16T17:00:00Z',
    currentDate: '2024-01-17T12:00:00Z',
    daysDelayed: 1,
    status: 'SHIPPED',
    currentLocation: 'Out for Delivery',
    courier: 'QuickDeliver',
    trackingNumber: 'QD987654321',
    total: 125.50,
    items: 1,
    delayReason: 'Address verification required',
  },
  {
    id: 'order-delayed-003',
    orderId: 'ORD-2024-008',
    buyer: 'Carol Davis',
    buyerEmail: 'carol@example.com',
    orderDate: '2024-01-08T09:00:00Z',
    expectedDeliveryDate: '2024-01-13T17:00:00Z',
    currentDate: '2024-01-17T12:00:00Z',
    daysDelayed: 4,
    status: 'PROCESSING',
    currentLocation: 'Warehouse',
    courier: null,
    trackingNumber: null,
    total: 890.00,
    items: 3,
    delayReason: 'Stock shortage - awaiting restock',
  },
  {
    id: 'order-delayed-004',
    orderId: 'ORD-2024-009',
    buyer: 'Eve Martinez',
    buyerEmail: 'eve@example.com',
    orderDate: '2024-01-11T11:15:00Z',
    expectedDeliveryDate: '2024-01-15T17:00:00Z',
    currentDate: '2024-01-17T12:00:00Z',
    daysDelayed: 2,
    status: 'SHIPPED',
    currentLocation: 'In Transit - Regional Hub',
    courier: 'Global Logistics',
    trackingNumber: 'GL456789123',
    total: 2100.75,
    items: 5,
    delayReason: 'Logistics delay',
  },
]

// Courier Options for Bulk Assignment
export const courierOptions = [
  { id: 'fastship', name: 'FastShip Express', estimatedDays: 2 },
  { id: 'quickdeliver', name: 'QuickDeliver', estimatedDays: 3 },
  { id: 'globallogistics', name: 'Global Logistics', estimatedDays: 4 },
  { id: 'standardpost', name: 'Standard Post', estimatedDays: 5 },
]

