// Mock data for Seller Management module

// Seller Performance Data
export const sellerPerformanceData = [
  {
    id: 1,
    sellerId: 'seller-001',
    businessName: 'TechGadgets Pro',
    email: 'tech@example.com',
    phone: '+1234567890',
    performanceScore: 92,
    deliveryTime: 2.1, // days average
    customerRating: 4.8,
    totalOrders: 1245,
    completedOrders: 1198,
    cancelledOrders: 12,
    delayedOrders: 35,
    onTimeDeliveryRate: 96.2,
    category: 'top',
  },
  {
    id: 2,
    sellerId: 'seller-002',
    businessName: 'Fashion Hub',
    email: 'fashion@example.com',
    phone: '+1234567891',
    performanceScore: 85,
    deliveryTime: 2.5,
    customerRating: 4.6,
    totalOrders: 892,
    completedOrders: 856,
    cancelledOrders: 8,
    delayedOrders: 28,
    onTimeDeliveryRate: 93.1,
    category: 'top',
  },
  {
    id: 3,
    sellerId: 'seller-003',
    businessName: 'Home Essentials',
    email: 'home@example.com',
    phone: '+1234567892',
    performanceScore: 78,
    deliveryTime: 3.2,
    customerRating: 4.2,
    totalOrders: 567,
    completedOrders: 534,
    cancelledOrders: 15,
    delayedOrders: 18,
    onTimeDeliveryRate: 87.5,
    category: 'average',
  },
  {
    id: 4,
    sellerId: 'seller-004',
    businessName: 'Sports World',
    email: 'sports@example.com',
    phone: '+1234567893',
    performanceScore: 65,
    deliveryTime: 4.8,
    customerRating: 3.8,
    totalOrders: 234,
    completedOrders: 201,
    cancelledOrders: 18,
    delayedOrders: 15,
    onTimeDeliveryRate: 75.2,
    category: 'low',
  },
  {
    id: 5,
    sellerId: 'seller-005',
    businessName: 'Electronics Plus',
    email: 'electronics@example.com',
    phone: '+1234567894',
    performanceScore: 58,
    deliveryTime: 5.5,
    customerRating: 3.4,
    totalOrders: 156,
    completedOrders: 128,
    cancelledOrders: 22,
    delayedOrders: 6,
    onTimeDeliveryRate: 68.3,
    category: 'low',
  },
  {
    id: 6,
    sellerId: 'seller-006',
    businessName: 'Books & More',
    email: 'books@example.com',
    phone: '+1234567895',
    performanceScore: 88,
    deliveryTime: 2.3,
    customerRating: 4.7,
    totalOrders: 678,
    completedOrders: 654,
    cancelledOrders: 5,
    delayedOrders: 19,
    onTimeDeliveryRate: 94.8,
    category: 'top',
  },
]

// Seller Wallet & Payout Data
export const sellerWalletData = [
  {
    sellerId: 'seller-001',
    businessName: 'TechGadgets Pro',
    wallet: {
      totalEarnings: 125000,
      pendingPayouts: 15000,
      completedPayouts: 110000,
      availableBalance: 125000 - 15000, // total - pending
    },
    withdrawRequests: [
      {
        id: 'req-001',
        amount: 5000,
        status: 'pending',
        requestDate: '2024-01-15',
        processedDate: null,
        reason: null,
      },
      {
        id: 'req-002',
        amount: 10000,
        status: 'approved',
        requestDate: '2024-01-10',
        processedDate: '2024-01-12',
        reason: null,
      },
      {
        id: 'req-003',
        amount: 8000,
        status: 'rejected',
        requestDate: '2024-01-05',
        processedDate: '2024-01-06',
        reason: 'Insufficient documentation',
      },
    ],
  },
  {
    sellerId: 'seller-002',
    businessName: 'Fashion Hub',
    wallet: {
      totalEarnings: 89000,
      pendingPayouts: 12000,
      completedPayouts: 77000,
      availableBalance: 77000,
    },
    withdrawRequests: [
      {
        id: 'req-004',
        amount: 12000,
        status: 'pending',
        requestDate: '2024-01-16',
        processedDate: null,
        reason: null,
      },
      {
        id: 'req-005',
        amount: 15000,
        status: 'approved',
        requestDate: '2024-01-08',
        processedDate: '2024-01-10',
        reason: null,
      },
    ],
  },
  {
    sellerId: 'seller-003',
    businessName: 'Home Essentials',
    wallet: {
      totalEarnings: 56000,
      pendingPayouts: 5000,
      completedPayouts: 51000,
      availableBalance: 51000,
    },
    withdrawRequests: [
      {
        id: 'req-006',
        amount: 5000,
        status: 'pending',
        requestDate: '2024-01-14',
        processedDate: null,
        reason: null,
      },
    ],
  },
  {
    sellerId: 'seller-004',
    businessName: 'Sports World',
    wallet: {
      totalEarnings: 23000,
      pendingPayouts: 3000,
      completedPayouts: 20000,
      availableBalance: 20000,
    },
    withdrawRequests: [],
  },
  {
    sellerId: 'seller-005',
    businessName: 'Electronics Plus',
    wallet: {
      totalEarnings: 15000,
      pendingPayouts: 2000,
      completedPayouts: 13000,
      availableBalance: 13000,
    },
    withdrawRequests: [
      {
        id: 'req-007',
        amount: 2000,
        status: 'pending',
        requestDate: '2024-01-17',
        processedDate: null,
        reason: null,
      },
    ],
  },
  {
    sellerId: 'seller-006',
    businessName: 'Books & More',
    wallet: {
      totalEarnings: 67000,
      pendingPayouts: 8000,
      completedPayouts: 59000,
      availableBalance: 59000,
    },
    withdrawRequests: [
      {
        id: 'req-008',
        amount: 8000,
        status: 'approved',
        requestDate: '2024-01-11',
        processedDate: '2024-01-13',
        reason: null,
      },
    ],
  },
]

// Seller Verification Data
export const sellerVerificationData = [
  {
    sellerId: 'seller-001',
    businessName: 'TechGadgets Pro',
    email: 'tech@example.com',
    verificationStatus: 'approved',
    submittedDate: '2024-01-05',
    reviewedDate: '2024-01-07',
    reviewedBy: 'Admin User',
    documents: {
      cnic: {
        status: 'approved',
        uploadedDate: '2024-01-05',
        fileName: 'cnic-front-back.pdf',
        url: '#',
      },
      businessLicense: {
        status: 'approved',
        uploadedDate: '2024-01-05',
        fileName: 'business-license.pdf',
        url: '#',
      },
      taxCertificate: {
        status: 'approved',
        uploadedDate: '2024-01-05',
        fileName: 'tax-certificate.pdf',
        url: '#',
      },
      bankStatement: {
        status: 'approved',
        uploadedDate: '2024-01-05',
        fileName: 'bank-statement.pdf',
        url: '#',
      },
    },
    rejectionReason: null,
  },
  {
    sellerId: 'seller-002',
    businessName: 'Fashion Hub',
    email: 'fashion@example.com',
    verificationStatus: 'approved',
    submittedDate: '2024-01-03',
    reviewedDate: '2024-01-06',
    reviewedBy: 'Admin User',
    documents: {
      cnic: {
        status: 'approved',
        uploadedDate: '2024-01-03',
        fileName: 'cnic.pdf',
        url: '#',
      },
      businessLicense: {
        status: 'approved',
        uploadedDate: '2024-01-03',
        fileName: 'license.pdf',
        url: '#',
      },
      taxCertificate: {
        status: 'approved',
        uploadedDate: '2024-01-03',
        fileName: 'tax.pdf',
        url: '#',
      },
      bankStatement: {
        status: 'approved',
        uploadedDate: '2024-01-03',
        fileName: 'bank.pdf',
        url: '#',
      },
    },
    rejectionReason: null,
  },
  {
    sellerId: 'seller-003',
    businessName: 'Home Essentials',
    email: 'home@example.com',
    verificationStatus: 'pending',
    submittedDate: '2024-01-12',
    reviewedDate: null,
    reviewedBy: null,
    documents: {
      cnic: {
        status: 'pending',
        uploadedDate: '2024-01-12',
        fileName: 'cnic.pdf',
        url: '#',
      },
      businessLicense: {
        status: 'pending',
        uploadedDate: '2024-01-12',
        fileName: 'license.pdf',
        url: '#',
      },
      taxCertificate: {
        status: 'pending',
        uploadedDate: '2024-01-12',
        fileName: 'tax.pdf',
        url: '#',
      },
      bankStatement: {
        status: 'missing',
        uploadedDate: null,
        fileName: null,
        url: null,
      },
    },
    rejectionReason: null,
  },
  {
    sellerId: 'seller-004',
    businessName: 'Sports World',
    email: 'sports@example.com',
    verificationStatus: 'rejected',
    submittedDate: '2024-01-08',
    reviewedDate: '2024-01-10',
    reviewedBy: 'Admin User',
    documents: {
      cnic: {
        status: 'rejected',
        uploadedDate: '2024-01-08',
        fileName: 'cnic-blurry.pdf',
        url: '#',
        rejectionReason: 'Image quality too low, please upload clear scan',
      },
      businessLicense: {
        status: 'pending',
        uploadedDate: '2024-01-08',
        fileName: 'license.pdf',
        url: '#',
      },
      taxCertificate: {
        status: 'missing',
        uploadedDate: null,
        fileName: null,
        url: null,
      },
      bankStatement: {
        status: 'missing',
        uploadedDate: null,
        fileName: null,
        url: null,
      },
    },
    rejectionReason: 'Incomplete documentation and poor image quality',
  },
  {
    sellerId: 'seller-005',
    businessName: 'Electronics Plus',
    email: 'electronics@example.com',
    verificationStatus: 'pending',
    submittedDate: '2024-01-15',
    reviewedDate: null,
    reviewedBy: null,
    documents: {
      cnic: {
        status: 'pending',
        uploadedDate: '2024-01-15',
        fileName: 'cnic.pdf',
        url: '#',
      },
      businessLicense: {
        status: 'missing',
        uploadedDate: null,
        fileName: null,
        url: null,
      },
      taxCertificate: {
        status: 'missing',
        uploadedDate: null,
        fileName: null,
        url: null,
      },
      bankStatement: {
        status: 'missing',
        uploadedDate: null,
        fileName: null,
        url: null,
      },
    },
    rejectionReason: null,
  },
  {
    sellerId: 'seller-006',
    businessName: 'Books & More',
    email: 'books@example.com',
    verificationStatus: 'approved',
    submittedDate: '2024-01-04',
    reviewedDate: '2024-01-06',
    reviewedBy: 'Admin User',
    documents: {
      cnic: {
        status: 'approved',
        uploadedDate: '2024-01-04',
        fileName: 'cnic.pdf',
        url: '#',
      },
      businessLicense: {
        status: 'approved',
        uploadedDate: '2024-01-04',
        fileName: 'license.pdf',
        url: '#',
      },
      taxCertificate: {
        status: 'approved',
        uploadedDate: '2024-01-04',
        fileName: 'tax.pdf',
        url: '#',
      },
      bankStatement: {
        status: 'approved',
        uploadedDate: '2024-01-04',
        fileName: 'bank.pdf',
        url: '#',
      },
    },
    rejectionReason: null,
  },
]

// Low Stock Alerts Data
export const lowStockAlertsData = [
  {
    id: 1,
    sellerId: 'seller-001',
    sellerName: 'TechGadgets Pro',
    productId: 'prod-001',
    productName: 'Wireless Earbuds Pro',
    currentStock: 5,
    threshold: 20,
    status: 'critical', // critical, warning, low
    lastRestocked: '2024-01-10',
    daysSinceRestock: 7,
  },
  {
    id: 2,
    sellerId: 'seller-001',
    sellerName: 'TechGadgets Pro',
    productId: 'prod-002',
    productName: 'USB-C Fast Charger',
    currentStock: 12,
    threshold: 30,
    status: 'warning',
    lastRestocked: '2024-01-08',
    daysSinceRestock: 9,
  },
  {
    id: 3,
    sellerId: 'seller-002',
    sellerName: 'Fashion Hub',
    productId: 'prod-003',
    productName: 'Designer T-Shirt',
    currentStock: 3,
    threshold: 15,
    status: 'critical',
    lastRestocked: '2024-01-05',
    daysSinceRestock: 12,
  },
  {
    id: 4,
    sellerId: 'seller-002',
    sellerName: 'Fashion Hub',
    productId: 'prod-004',
    productName: 'Jeans Classic',
    currentStock: 18,
    threshold: 25,
    status: 'low',
    lastRestocked: '2024-01-12',
    daysSinceRestock: 5,
  },
  {
    id: 5,
    sellerId: 'seller-003',
    sellerName: 'Home Essentials',
    productId: 'prod-005',
    productName: 'Kitchen Knife Set',
    currentStock: 2,
    threshold: 10,
    status: 'critical',
    lastRestocked: '2024-01-03',
    daysSinceRestock: 14,
  },
  {
    id: 6,
    sellerId: 'seller-004',
    sellerName: 'Sports World',
    productId: 'prod-006',
    productName: 'Running Shoes',
    currentStock: 8,
    threshold: 20,
    status: 'warning',
    lastRestocked: '2024-01-11',
    daysSinceRestock: 6,
  },
  {
    id: 7,
    sellerId: 'seller-005',
    sellerName: 'Electronics Plus',
    productId: 'prod-007',
    productName: 'Smartphone Case',
    currentStock: 1,
    threshold: 15,
    status: 'critical',
    lastRestocked: '2024-01-01',
    daysSinceRestock: 16,
  },
  {
    id: 8,
    sellerId: 'seller-006',
    sellerName: 'Books & More',
    productId: 'prod-008',
    productName: 'Best Seller Book',
    currentStock: 15,
    threshold: 30,
    status: 'low',
    lastRestocked: '2024-01-13',
    daysSinceRestock: 4,
  },
]

